/**
 * subtitles.ts — burned-in cues, in frames at 30fps.
 *
 * TIMING is the corrected SRT's, verbatim. WORDING is that file's too — it is
 * the corrected one, so what is on screen is what was written, not what the
 * first pass transcribed. Generated from `Moving_Average_VO_2_CORRECTED.srt`,
 * never hand-typed.
 *
 * Where the SRT let one cue start before the previous had ended, the earlier
 * cue is truncated to the later one's start. Two cues on screen at once in a
 * band this size is two lines of type overlapping, which the episode forbids.
 *
 * These live in the reserved bottom 108px band, which every scene keeps clear.
 */
export type Cue = { start: number; end: number; text: string };

export const CUES: Cue[] = [
  { start: 0, end: 79, text: "Membaca candlestick dan chart pattern memang powerful." },
  { start: 96, end: 149, text: "Tapi kalau harus cek saham satu per satu," },
  { start: 157, end: 234, text: "prosesnya bisa cukup lama dan butuh mata yang terlatih." },
  { start: 237, end: 282, text: "Di sinilah indikator membantu." },
  { start: 303, end: 366, text: "Indikator mengolah data harga yang sudah ada" },
  { start: 366, end: 421, text: "supaya chart lebih cepat dibaca." },
  { start: 437, end: 483, text: "Bukan menggantikan analisismu," },
  { start: 487, end: 584, text: "tapi membantu menyaring chart dan mengonfirmasi apa yang kamu lihat." },
  { start: 607, end: 667, text: "Kita mulai dari moving average." },
  { start: 679, end: 749, text: "Harga bergerak naik-turun dan penuh noise." },
  { start: 758, end: 821, text: "Moving average mengambil rata-rata harga" },
  { start: 825, end: 851, text: "beberapa hari terakhir," },
  { start: 860, end: 939, text: "lalu menggambarkannya sebagai garis yang lebih halus." },
  { start: 961, end: 1004, text: "Setiap hari, garisnya ikut bergerak." },
  { start: 1011, end: 1093, text: "Noise berkurang dan arah trend jadi lebih mudah terlihat." },
  { start: 1106, end: 1173, text: "Angkanya menunjukkan berapa periode yang dihitung." },
  { start: 1182, end: 1223, text: "Moving average pendek," },
  { start: 1233, end: 1278, text: "misalnya MA20," },
  { start: 1291, end: 1333, text: "bergerak lebih dekat dengan harga" },
  { start: 1339, end: 1379, text: "dan bereaksi lebih cepat." },
  { start: 1392, end: 1423, text: "Moving average panjang," },
  { start: 1427, end: 1457, text: "seperti MA200," },
  { start: 1466, end: 1513, text: "bergerak lebih lambat dan membantu" },
  { start: 1520, end: 1563, text: "melihat trend yang lebih besar." },
  { start: 1583, end: 1637, text: "Jadi, yang pendek lebih responsif." },
  { start: 1640, end: 1683, text: "Yang panjang memberi big picture." },
  { start: 1687, end: 1755, text: "Karena itu, trader sering melihat keduanya." },
  { start: 1765, end: 1803, text: "Ada dua jenis yang sering dipakai:" },
  { start: 1823, end: 1887, text: "SMA dan EMA." },
  { start: 1909, end: 1997, text: "SMA memberi bobot yang sama pada setiap harga." },
  { start: 2021, end: 2118, text: "EMA memberi bobot lebih besar pada harga terbaru," },
  { start: 2129, end: 2168, text: "jadi reaksinya lebih cepat." },
  { start: 2190, end: 2235, text: "Tapi lebih cepat bukan selalu lebih baik," },
  { start: 2243, end: 2309, text: "karena false signal juga bisa lebih sering muncul." },
  { start: 2324, end: 2379, text: "Cara paling sederhana membacanya begini." },
  { start: 2387, end: 2445, text: "Harga di atas moving average yang menanjak" },
  { start: 2448, end: 2487, text: "biasanya menunjukkan uptrend." },
  { start: 2495, end: 2552, text: "Harga di bawah moving average yang menurun" },
  { start: 2556, end: 2589, text: "menunjukkan downtrend." },
  { start: 2594, end: 2628, text: "Perhatikan juga slope-nya." },
  { start: 2630, end: 2690, text: "Semakin curam garisnya, semakin kuat trend." },
  { start: 2693, end: 2753, text: "Kalau datar, market belum punya arah yang jelas." },
  { start: 2777, end: 2811, text: "Jadi, lihat dua hal:" },
  { start: 2822, end: 2893, text: "posisi harga dan arah moving average." },
  { start: 2903, end: 2967, text: "Moving average juga bisa berfungsi sebagai support" },
  { start: 2976, end: 3025, text: "atau resistance yang bergerak." },
  { start: 3035, end: 3099, text: "Dalam uptrend, harga sering pullback ke MA" },
  { start: 3107, end: 3127, text: "yang menanjak," },
  { start: 3127, end: 3192, text: "lalu memantul seperti lantai yang ikut naik." },
  { start: 3215, end: 3243, text: "Dalam downtrend," },
  { start: 3246, end: 3348, text: "MA bisa menahan harga dari atas seperti langit-langit." },
  { start: 3353, end: 3415, text: "Konsepnya sama seperti support dan resistance," },
  { start: 3422, end: 3490, text: "hanya levelnya ikut bergerak bersama harga." },
  { start: 3490, end: 3535, text: "Saat moving average pendek" },
  { start: 3536, end: 3588, text: "menembus moving average panjang dari bawah," },
  { start: 3595, end: 3639, text: "ini disebut golden cross." },
  { start: 3645, end: 3690, text: "Kalau menembus dari atas ke bawah," },
  { start: 3695, end: 3732, text: "disebut death cross." },
  { start: 3749, end: 3842, text: "Tapi jangan anggap crossing sebagai aba-aba entry atau exit." },
  { start: 3848, end: 3905, text: "Moving average bersifat lagging." },
  { start: 3918, end: 3948, text: "Saat crossing muncul," },
  { start: 3955, end: 4019, text: "sebagian pergerakan biasanya sudah terjadi." },
  { start: 4037, end: 4089, text: "Gunakan sebagai konfirmasi trend," },
  { start: 4094, end: 4129, text: "bukan untuk meramal." },
  { start: 4140, end: 4195, text: "Sekarang masuk ke Bollinger Bands." },
  { start: 4205, end: 4273, text: "Di tengahnya ada moving average." },
  { start: 4291, end: 4322, text: "Di atas dan bawahnya," },
  { start: 4327, end: 4403, text: "dua band ikut berubah sesuai volatility —" },
  { start: 4406, end: 4484, text: "seberapa besar pergerakan harga dari rata-ratanya." },
  { start: 4494, end: 4547, text: "Saat market tenang, band menyempit." },
  { start: 4551, end: 4614, text: "Saat pergerakan membesar, band ikut melebar." },
  { start: 4622, end: 4707, text: "Bollinger Bands seperti bernapas mengikuti energi pasar." },
  { start: 4731, end: 4782, text: "Salah satu kondisi yang paling berguna" },
  { start: 4785, end: 4825, text: "diperhatikan adalah squeeze." },
  { start: 4835, end: 4867, text: "Saat band menyempit rapat," },
  { start: 4871, end: 4965, text: "volatility sedang rendah dan harga biasanya bergerak sideways." },
  { start: 4979, end: 5022, text: "Kondisi seperti ini sering muncul" },
  { start: 5025, end: 5070, text: "sebelum pergerakan yang lebih besar." },
  { start: 5083, end: 5154, text: "Tapi squeeze tidak memberi tahu arahnya." },
  { start: 5162, end: 5223, text: "Harga bisa breakout ke atas atau ke bawah." },
  { start: 5244, end: 5288, text: "Jadi, tetap lihat trend" },
  { start: 5288, end: 5355, text: "dan level penting sebelum mengambil kesimpulan." },
  { start: 5366, end: 5449, text: "Ada satu jebakan yang sering terjadi pada pemula." },
  { start: 5460, end: 5485, text: "Dalam trend kuat," },
  { start: 5502, end: 5564, text: "harga bisa terus bergerak dekat upper band." },
  { start: 5573, end: 5660, text: "Jadi, menyentuh upper band bukan otomatis sinyal jual." },
  { start: 5671, end: 5707, text: "Dalam uptrend sehat," },
  { start: 5712, end: 5756, text: "kondisi ini justru bisa menunjukkan" },
  { start: 5760, end: 5820, text: "harga masih bergerak dengan momentum kuat." },
  { start: 5835, end: 5893, text: "Bollinger Bands menunjukkan posisi harga" },
  { start: 5893, end: 5984, text: "terhadap rata-ratanya, bukan memberi keputusan entry atau exit." },
  { start: 5999, end: 6051, text: "Lalu, di mana indikator digunakan?" },
  { start: 6066, end: 6114, text: "Fondasinya tetap price action:" },
  { start: 6135, end: 6173, text: "trend, pattern," },
  { start: 6185, end: 6248, text: "support, dan resistance" },
  { start: 6255, end: 6307, text: "yang kamu baca lebih dulu." },
  { start: 6307, end: 6368, text: "Moving average membantu mengonfirmasi trend." },
  { start: 6373, end: 6410, text: "Bollinger Bands membantu" },
  { start: 6414, end: 6452, text: "melihat apakah volatility" },
  { start: 6456, end: 6500, text: "sedang menyempit atau melebar." },
  { start: 6510, end: 6565, text: "Anggap indikator sebagai second opinion," },
  { start: 6569, end: 6630, text: "bukan alat yang mengambil keputusan untukmu." },
  { start: 6645, end: 6692, text: "Sekarang giliran kamu." },
  { start: 6692, end: 6789, text: "Ini chart GGRM pada Juli 2026." },
  { start: 6836, end: 6901, text: "Harga turun ke moving average yang lebih lambat" },
  { start: 6903, end: 6927, text: "dan menanjak," },
  { start: 6931, end: 6963, text: "yaitu garis ungu," },
  { start: 6969, end: 7001, text: "lalu memantul." },
  { start: 7010, end: 7033, text: "Beberapa hari kemudian," },
  { start: 7033, end: 7091, text: "Bollinger Bands menyempit menjadi squeeze," },
  { start: 7095, end: 7182, text: "sementara harga masih bertahan sedikit di atas middle band." },
  { start: 7182, end: 7249, text: "Menurutmu, apakah uptrend-nya masih bertahan?" },
  { start: 7271, end: 7327, text: "Dan saat band serapat ini," },
  { start: 7332, end: 7384, text: "apa yang perlu kita antisipasi?" },
  { start: 7384, end: 7490, text: "Tiga… dua… satu." },
  { start: 7503, end: 7569, text: "Dan ternyata, harga breakout ke atas." },
  { start: 7580, end: 7639, text: "Moving average yang menanjak sebelumnya" },
  { start: 7641, end: 7675, text: "berhasil menjadi support." },
  { start: 7685, end: 7709, text: "Setelah squeeze," },
  { start: 7712, end: 7758, text: "Bollinger Bands kembali melebar" },
  { start: 7760, end: 7835, text: "dan harga melanjutkan kenaikan hingga awal Agustus" },
  { start: 7842, end: 7917, text: "menuju sekitar 20.350." },
  { start: 7927, end: 8013, text: "Jadi, bullish bias-nya datang dari trend yang masih terjaga." },
  { start: 8032, end: 8103, text: "Squeeze hanya memberi tahu bahwa pergerakan besar" },
  { start: 8107, end: 8136, text: "mungkin segera terjadi." },
  { start: 8158, end: 8182, text: "Dalam kasus ini," },
  { start: 8182, end: 8261, text: "arah breakout sesuai dengan trend yang sudah terbentuk." },
  { start: 8271, end: 8339, text: "Ingat, indikator tidak pernah memimpin harga." },
  { start: 8355, end: 8406, text: "Indikator mengikuti data yang sudah terjadi," },
  { start: 8417, end: 8526, text: "lalu membantu mengonfirmasi atau mempertanyakan analisismu." },
  { start: 8535, end: 8604, text: "Gunakan moving average untuk membaca trend," },
  { start: 8619, end: 8700, text: "Bollinger Bands untuk melihat perubahan volatility," },
  { start: 8715, end: 8775, text: "dan tetap mulai dari price action." },
  { start: 8787, end: 8839, text: "Tapi jangan pernah mengambil keputusan" },
  { start: 8846, end: 8895, text: "hanya karena satu indikator." },
];
