/**
 * subtitles.ts — burned-in cues, in frames at 30fps.
 *
 * TIMING is the corrected SRT's, verbatim. WORDING is that file's too — it is
 * the corrected one, so what is on screen is what was written, not what the
 * first pass transcribed. Generated from the .srt, never hand-typed.
 *
 * Where the SRT let one cue start before the previous had ended, the earlier
 * cue is truncated to the later one's start. Two cues on screen at once in a
 * band this size is two lines of type overlapping, which the episode forbids.
 *
 * These live in the reserved bottom 108px band, which every scene keeps clear.
 */
export type Cue = { start: number; end: number; text: string };

export const CUES: Cue[] = [
  { start: 3, end: 92, text: "Membaca candlestick dan chart pattern memang powerful." },
  { start: 101, end: 185, text: "Tapi prosesnya lambat dan butuh mata terlatih." },
  { start: 196, end: 249, text: "Kamu harus membuka saham satu per satu" },
  { start: 254, end: 296, text: "dan membacanya manual." },
  { start: 309, end: 392, text: "Nah, indikator membantu kita bekerja lebih cepat." },
  { start: 412, end: 488, text: "Indikator hanya mengolah data harga yang sudah ada." },
  { start: 508, end: 552, text: "Bukan menggantikan analisis," },
  { start: 558, end: 650, text: "tetapi menyaring chart dan mengonfirmasi pembacaanmu." },
  { start: 659, end: 713, text: "Kita mulai dari moving average." },
  { start: 724, end: 791, text: "Harga bergerak naik-turun dan penuh noise." },
  { start: 791, end: 880, text: "Moving average mengambil rata-rata harga beberapa hari terakhir," },
  { start: 888, end: 950, text: "lalu menggambarkannya sebagai garis halus." },
  { start: 963, end: 1008, text: "Setiap hari, garisnya ikut bergerak." },
  { start: 1020, end: 1116, text: "Noise tersaring dan arah utamanya terlihat lebih jelas." },
  { start: 1146, end: 1178, text: "Angkanya menunjukkan" },
  { start: 1186, end: 1232, text: "berapa hari yang dihitung." },
  { start: 1241, end: 1314, text: "Moving average pendek, seperti 20 hari," },
  { start: 1323, end: 1395, text: "bergerak dekat dengan harga dan bereaksi cepat." },
  { start: 1408, end: 1442, text: "Moving average panjang," },
  { start: 1450, end: 1480, text: "seperti 200 hari," },
  { start: 1492, end: 1575, text: "bergerak lebih lambat dan menunjukkan arah besarnya." },
  { start: 1587, end: 1646, text: "Yang pendek membaca pergerakan dekat." },
  { start: 1660, end: 1724, text: "Yang panjang menunjukkan arus utama." },
  { start: 1742, end: 1826, text: "Karena itu, banyak trader memakai keduanya." },
  { start: 1839, end: 1943, text: "Ada dua jenis: SMA dan EMA." },
  { start: 1971, end: 2044, text: "SMA memberi bobot sama setiap hari." },
  { start: 2060, end: 2171, text: "EMA lebih menekankan harga terbaru dan bereaksi cepat." },
  { start: 2192, end: 2242, text: "Tapi cepat bukan selalu lebih baik karena" },
  { start: 2247, end: 2292, text: "false signal lebih sering muncul." },
  { start: 2306, end: 2375, text: "Cara sederhana membacanya begini." },
  { start: 2391, end: 2486, text: "Harga di atas moving average yang menanjak menunjukkan trend naik." },
  { start: 2486, end: 2579, text: "Harga di bawah garis menurun menunjukkan trend turun." },
  { start: 2592, end: 2693, text: "Perhatikan slope-nya. Semakin curam, semakin kuat trend." },
  { start: 2700, end: 2774, text: "Kalau datar, pasar belum punya arah jelas." },
  { start: 2795, end: 2866, text: "Jadi, lihat posisi harga dan arah garis." },
  { start: 2882, end: 2942, text: "Moving average juga bisa menjadi support" },
  { start: 2945, end: 3002, text: "atau resistance yang bergerak." },
  { start: 3008, end: 3101, text: "Dalam uptrend, harga sering pullback ke garis yang menanjak" },
  { start: 3106, end: 3135, text: "lalu memantul," },
  { start: 3152, end: 3198, text: "seperti lantai yang ikut naik." },
  { start: 3209, end: 3284, text: "Dalam downtrend, garisnya menahan harga dari atas" },
  { start: 3288, end: 3317, text: "seperti langit-langit." },
  { start: 3328, end: 3352, text: "Konsepnya sama," },
  { start: 3354, end: 3424, text: "hanya levelnya terus bergerak mengikuti harga." },
  { start: 3444, end: 3497, text: "Saat moving average pendek menembus" },
  { start: 3501, end: 3544, text: "moving average panjang dari bawah," },
  { start: 3554, end: 3611, text: "trader menyebutnya golden cross." },
  { start: 3617, end: 3675, text: "Kebalikannya disebut death cross." },
  { start: 3695, end: 3795, text: "Tapi jangan anggap crossing sebagai aba-aba entry." },
  { start: 3807, end: 3875, text: "Moving average bersifat lagging." },
  { start: 3886, end: 3916, text: "Saat crossing muncul," },
  { start: 3923, end: 3985, text: "sebagian pergerakan sudah terjadi." },
  { start: 3985, end: 4059, text: "Gunakan sebagai konfirmasi trend," },
  { start: 4068, end: 4124, text: "bukan untuk meramal." },
  { start: 4134, end: 4192, text: "Sekarang masuk ke Bollinger Bands." },
  { start: 4192, end: 4248, text: "Di tengahnya ada moving average." },
  { start: 4254, end: 4337, text: "Di atas dan bawahnya, dua band mengukur volatility," },
  { start: 4346, end: 4430, text: "atau seberapa jauh harga bergerak dari rata-ratanya." },
  { start: 4442, end: 4520, text: "Saat pasar tenang, band menyempit." },
  { start: 4538, end: 4631, text: "Saat pergerakan membesar, band melebar." },
  { start: 4631, end: 4719, text: "Bollinger Bands seperti bernapas mengikuti energi pasar." },
  { start: 4738, end: 4796, text: "Sinyal paling berguna adalah squeeze." },
  { start: 4810, end: 4854, text: "Saat band menyempit rapat," },
  { start: 4864, end: 4949, text: "volatility rendah dan harga biasanya sideways." },
  { start: 4960, end: 5015, text: "Pembeli dan penjual sama-sama menunggu." },
  { start: 5034, end: 5084, text: "Kondisi tenang ini jarang bertahan lama." },
  { start: 5094, end: 5172, text: "Squeeze sering muncul sebelum pergerakan besar." },
  { start: 5187, end: 5264, text: "Tapi ia hanya memberi tahu gerakan mungkin datang," },
  { start: 5276, end: 5306, text: "bukan arahnya." },
  { start: 5306, end: 5414, text: "Jadi, tetap baca trend dan level penting." },
  { start: 5439, end: 5508, text: "Ada satu jebakan untuk pemula." },
  { start: 5518, end: 5547, text: "Dalam trend kuat," },
  { start: 5556, end: 5625, text: "harga bisa terus menempel di upper band." },
  { start: 5639, end: 5722, text: "Sentuhan ke upper band bukan otomatis sinyal jual." },
  { start: 5738, end: 5832, text: "Dalam trend sehat, ini justru menunjukkan kekuatan." },
  { start: 5847, end: 5944, text: "Bollinger Bands hanya menunjukkan jarak harga dari rata-ratanya," },
  { start: 5951, end: 6016, text: "bukan keputusan entry atau exit." },
  { start: 6034, end: 6088, text: "Lalu, di mana indikator digunakan?" },
  { start: 6105, end: 6184, text: "Fondasinya tetap analisismu sendiri: trend," },
  { start: 6191, end: 6264, text: "pattern, dan level yang kamu tandai." },
  { start: 6280, end: 6347, text: "Moving average membantu mengonfirmasi trend." },
  { start: 6362, end: 6422, text: "Bollinger Bands menunjukkan apakah pasar" },
  { start: 6432, end: 6456, text: "sedang mengencang" },
  { start: 6472, end: 6504, text: "atau sudah bergerak kuat." },
  { start: 6522, end: 6580, text: "Anggap keduanya sebagai second opinion," },
  { start: 6586, end: 6657, text: "bukan alat yang mengambil keputusan untukmu." },
  { start: 6670, end: 6712, text: "Sekarang giliran kamu." },
  { start: 6712, end: 6797, text: "Ini chart GGRM pada Juli 2026." },
  { start: 6797, end: 6861, text: "Harga turun ke moving average lambat" },
  { start: 6861, end: 6929, text: "yang menanjak, yaitu garis ungu," },
  { start: 6940, end: 6972, text: "lalu memantul." },
  { start: 6984, end: 7008, text: "Beberapa hari kemudian," },
  { start: 7014, end: 7083, text: "Bollinger Bands menyempit menjadi squeeze," },
  { start: 7091, end: 7169, text: "sementara harga bertahan sedikit di atas middle band." },
  { start: 7185, end: 7215, text: "Apakah trend masih naik" },
  { start: 7218, end: 7293, text: "karena moving average bertahan sebagai support?" },
  { start: 7301, end: 7347, text: "Saat band serapat ini," },
  { start: 7359, end: 7407, text: "apa yang biasanya terjadi?" },
  { start: 7407, end: 7487, text: "Tiga… dua… satu." },
  { start: 7509, end: 7594, text: "Dan ternyata, harga breakout ke atas." },
  { start: 7616, end: 7691, text: "Moving average yang menanjak berhasil menjadi support." },
  { start: 7698, end: 7725, text: "Squeeze terlepas," },
  { start: 7739, end: 7767, text: "lalu harga terus naik" },
  { start: 7770, end: 7881, text: "hingga awal Agustus menuju sekitar 20.350." },
  { start: 7900, end: 7976, text: "Dua indikator memberi pembacaan yang searah dengan" },
  { start: 7979, end: 8028, text: "uptrend yang sudah terbentuk." },
  { start: 8038, end: 8075, text: "Bukan jaminan, tetapi" },
  { start: 8092, end: 8183, text: "probabilitasnya memang lebih condong ke atas." },
  { start: 8216, end: 8318, text: "Kali ini, hasilnya sesuai dengan pembacaan kita." },
  { start: 8318, end: 8344, text: "Ingat," },
  { start: 8344, end: 8422, text: "indikator tidak pernah memimpin harga." },
  { start: 8438, end: 8475, text: "Indikator hanya mengikuti," },
  { start: 8493, end: 8594, text: "lalu membantu memperkuat atau mempertanyakan analisismu." },
  { start: 8604, end: 8655, text: "Gunakan untuk mengonfirmasi trend," },
  { start: 8658, end: 8710, text: "menemukan squeeze, dan menyaring" },
  { start: 8715, end: 8756, text: "chart yang layak diperhatikan." },
  { start: 8775, end: 8816, text: "Tapi jangan pernah mengambil" },
  { start: 8824, end: 8900, text: "keputusan hanya karena satu indikator." },
];
