/**
 * subtitles.ts — burned-in cues, in frames at 30fps.
 *
 * TIMING is the corrected SRT's, verbatim. WORDING is that file's too — it is
 * the corrected one, so what is on screen is what was written, not what the
 * first pass transcribed. Generated from `Moving_Average_VO_2_CORRECTED.srt`,
 * never hand-typed.
 *
 * Where the SRT let one cue start before the previous had ended, the earlier
 * cue is truncated to the later one's start. Two cues on screen at once in a
 * band this size is two lines of type overlapping, which the episode forbids.
 *
 * These live in the reserved bottom 108px band, which every scene keeps clear.
 *
 * ⚠ SHIFTED TWICE. Sixty frames of silence were inserted into the voice-over
 * at frame 600 so the roadmap has time to be read; every cue from 601 on moved
 * with it. That pad was then cut to 24 frames (audio only), so every cue that
 * took the first +60 moved back -36 to track the new, shorter pad — cues
 * always follow the AUDIO. SC01 and CG-A's own frame ranges in Composition.tsx
 * were deliberately NOT pulled back to match (Simon: "biarkan overlapping"),
 * so captions inside that span are the one place in the episode that can run
 * ahead of what the video is depicting, until that's reconciled.
 */
export type Cue = { start: number; end: number; text: string };

export const CUES: Cue[] = [
  { start: 0, end: 79, text: "Membaca candlestick dan chart pattern memang powerful." },
  { start: 96, end: 149, text: "Tapi kalau harus cek saham satu per satu," },
  { start: 157, end: 234, text: "prosesnya bisa cukup lama dan butuh mata yang terlatih." },
  { start: 237, end: 282, text: "Di sinilah indikator membantu." },
  { start: 303, end: 366, text: "Indikator mengolah data harga yang sudah ada" },
  { start: 366, end: 421, text: "supaya chart lebih cepat dibaca." },
  { start: 437, end: 483, text: "Bukan menggantikan analisismu," },
  { start: 487, end: 584, text: "tapi membantu menyaring chart dan mengonfirmasi apa yang kamu lihat." },
  { start: 631, end: 691, text: "Kita mulai dari moving average." },
  { start: 703, end: 773, text: "Harga bergerak naik-turun dan penuh noise." },
  { start: 782, end: 845, text: "Moving average mengambil rata-rata harga" },
  { start: 849, end: 875, text: "beberapa hari terakhir," },
  { start: 884, end: 963, text: "lalu menggambarkannya sebagai garis yang lebih halus." },
  { start: 985, end: 1028, text: "Setiap hari, garisnya ikut bergerak." },
  { start: 1035, end: 1117, text: "Noise berkurang dan arah trend jadi lebih mudah terlihat." },
  { start: 1130, end: 1197, text: "Angkanya menunjukkan berapa periode yang dihitung." },
  { start: 1206, end: 1247, text: "Moving average pendek," },
  { start: 1257, end: 1302, text: "misalnya MA20," },
  { start: 1315, end: 1357, text: "bergerak lebih dekat dengan harga" },
  { start: 1363, end: 1403, text: "dan bereaksi lebih cepat." },
  { start: 1416, end: 1447, text: "Moving average panjang," },
  { start: 1451, end: 1481, text: "seperti MA200," },
  { start: 1490, end: 1537, text: "bergerak lebih lambat dan membantu" },
  { start: 1544, end: 1587, text: "melihat trend yang lebih besar." },
  { start: 1607, end: 1661, text: "Jadi, yang pendek lebih responsif." },
  { start: 1664, end: 1707, text: "Yang panjang memberi big picture." },
  { start: 1711, end: 1779, text: "Karena itu, trader sering melihat keduanya." },
  { start: 1789, end: 1827, text: "Ada dua jenis yang sering dipakai:" },
  { start: 1847, end: 1911, text: "SMA dan EMA." },
  { start: 1933, end: 2021, text: "SMA memberi bobot yang sama pada setiap harga." },
  { start: 2045, end: 2142, text: "EMA memberi bobot lebih besar pada harga terbaru," },
  { start: 2153, end: 2192, text: "jadi reaksinya lebih cepat." },
  { start: 2214, end: 2259, text: "Tapi lebih cepat bukan selalu lebih baik," },
  { start: 2267, end: 2333, text: "karena false signal juga bisa lebih sering muncul." },
  { start: 2348, end: 2403, text: "Cara paling sederhana membacanya begini." },
  { start: 2411, end: 2469, text: "Harga di atas moving average yang menanjak" },
  { start: 2472, end: 2511, text: "biasanya menunjukkan uptrend." },
  { start: 2519, end: 2576, text: "Harga di bawah moving average yang menurun" },
  { start: 2580, end: 2613, text: "menunjukkan downtrend." },
  { start: 2618, end: 2652, text: "Perhatikan juga slope-nya." },
  { start: 2654, end: 2714, text: "Semakin curam garisnya, semakin kuat trend." },
  { start: 2717, end: 2777, text: "Kalau datar, market belum punya arah yang jelas." },
  { start: 2801, end: 2835, text: "Jadi, lihat dua hal:" },
  { start: 2846, end: 2917, text: "posisi harga dan arah moving average." },
  { start: 2927, end: 2991, text: "Moving average juga bisa berfungsi sebagai support" },
  { start: 3000, end: 3049, text: "atau resistance yang bergerak." },
  { start: 3059, end: 3123, text: "Dalam uptrend, harga sering pullback ke MA" },
  { start: 3131, end: 3151, text: "yang menanjak," },
  { start: 3151, end: 3216, text: "lalu memantul seperti lantai yang ikut naik." },
  { start: 3239, end: 3267, text: "Dalam downtrend," },
  { start: 3270, end: 3372, text: "MA bisa menahan harga dari atas seperti langit-langit." },
  { start: 3377, end: 3439, text: "Konsepnya sama seperti support dan resistance," },
  { start: 3446, end: 3514, text: "hanya levelnya ikut bergerak bersama harga." },
  { start: 3514, end: 3559, text: "Saat moving average pendek" },
  { start: 3560, end: 3612, text: "menembus moving average panjang dari bawah," },
  { start: 3619, end: 3663, text: "ini disebut golden cross." },
  { start: 3669, end: 3714, text: "Kalau menembus dari atas ke bawah," },
  { start: 3719, end: 3756, text: "disebut death cross." },
  { start: 3773, end: 3866, text: "Tapi jangan anggap crossing sebagai aba-aba entry atau exit." },
  { start: 3872, end: 3929, text: "Moving average bersifat lagging." },
  { start: 3942, end: 3972, text: "Saat crossing muncul," },
  { start: 3979, end: 4043, text: "sebagian pergerakan biasanya sudah terjadi." },
  { start: 4061, end: 4113, text: "Gunakan sebagai konfirmasi trend," },
  { start: 4118, end: 4153, text: "bukan untuk meramal." },
  { start: 4164, end: 4219, text: "Sekarang masuk ke Bollinger Bands." },
  { start: 4229, end: 4297, text: "Di tengahnya ada moving average." },
  { start: 4315, end: 4346, text: "Di atas dan bawahnya," },
  { start: 4351, end: 4427, text: "dua band ikut berubah sesuai volatility —" },
  { start: 4430, end: 4508, text: "seberapa besar pergerakan harga dari rata-ratanya." },
  { start: 4518, end: 4571, text: "Saat market tenang, band menyempit." },
  { start: 4575, end: 4638, text: "Saat pergerakan membesar, band ikut melebar." },
  { start: 4646, end: 4731, text: "Bollinger Bands seperti bernapas mengikuti energi pasar." },
  { start: 4755, end: 4806, text: "Salah satu kondisi yang paling berguna" },
  { start: 4809, end: 4849, text: "diperhatikan adalah squeeze." },
  { start: 4859, end: 4891, text: "Saat band menyempit rapat," },
  { start: 4895, end: 4989, text: "volatility sedang rendah dan harga biasanya bergerak sideways." },
  { start: 5003, end: 5046, text: "Kondisi seperti ini sering muncul" },
  { start: 5049, end: 5094, text: "sebelum pergerakan yang lebih besar." },
  { start: 5107, end: 5178, text: "Tapi squeeze tidak memberi tahu arahnya." },
  { start: 5186, end: 5247, text: "Harga bisa breakout ke atas atau ke bawah." },
  { start: 5268, end: 5312, text: "Jadi, tetap lihat trend" },
  { start: 5312, end: 5379, text: "dan level penting sebelum mengambil kesimpulan." },
  { start: 5390, end: 5473, text: "Ada satu jebakan yang sering terjadi pada pemula." },
  { start: 5484, end: 5509, text: "Dalam trend kuat," },
  { start: 5526, end: 5588, text: "harga bisa terus bergerak dekat upper band." },
  { start: 5597, end: 5684, text: "Jadi, menyentuh upper band bukan otomatis sinyal jual." },
  { start: 5695, end: 5731, text: "Dalam uptrend sehat," },
  { start: 5736, end: 5780, text: "kondisi ini justru bisa menunjukkan" },
  { start: 5784, end: 5844, text: "harga masih bergerak dengan momentum kuat." },
  { start: 5859, end: 5917, text: "Bollinger Bands menunjukkan posisi harga" },
  { start: 5917, end: 6008, text: "terhadap rata-ratanya, bukan memberi keputusan entry atau exit." },
  { start: 6023, end: 6075, text: "Lalu, di mana indikator digunakan?" },
  { start: 6090, end: 6138, text: "Fondasinya tetap price action:" },
  { start: 6159, end: 6197, text: "trend, pattern," },
  { start: 6209, end: 6272, text: "support, dan resistance" },
  { start: 6279, end: 6331, text: "yang kamu baca lebih dulu." },
  { start: 6331, end: 6392, text: "Moving average membantu mengonfirmasi trend." },
  { start: 6397, end: 6434, text: "Bollinger Bands membantu" },
  { start: 6438, end: 6476, text: "melihat apakah volatility" },
  { start: 6480, end: 6524, text: "sedang menyempit atau melebar." },
  { start: 6534, end: 6589, text: "Anggap indikator sebagai second opinion," },
  { start: 6593, end: 6654, text: "bukan alat yang mengambil keputusan untukmu." },
  { start: 6669, end: 6716, text: "Sekarang giliran kamu." },
  { start: 6716, end: 6813, text: "Ini chart GGRM pada Juli 2026." },
  { start: 6860, end: 6925, text: "Harga turun ke moving average yang lebih lambat" },
  { start: 6927, end: 6951, text: "dan menanjak," },
  { start: 6955, end: 6987, text: "yaitu garis ungu," },
  { start: 6993, end: 7025, text: "lalu memantul." },
  { start: 7034, end: 7057, text: "Beberapa hari kemudian," },
  { start: 7057, end: 7115, text: "Bollinger Bands menyempit menjadi squeeze," },
  { start: 7119, end: 7206, text: "sementara harga masih bertahan sedikit di atas middle band." },
  { start: 7206, end: 7273, text: "Menurutmu, apakah uptrend-nya masih bertahan?" },
  { start: 7295, end: 7351, text: "Dan saat band serapat ini," },
  { start: 7356, end: 7408, text: "apa yang perlu kita antisipasi?" },
  { start: 7408, end: 7514, text: "Tiga… dua… satu." },
  { start: 7527, end: 7593, text: "Dan ternyata, harga breakout ke atas." },
  { start: 7604, end: 7663, text: "Moving average yang menanjak sebelumnya" },
  { start: 7665, end: 7699, text: "berhasil menjadi support." },
  { start: 7709, end: 7733, text: "Setelah squeeze," },
  { start: 7736, end: 7782, text: "Bollinger Bands kembali melebar" },
  { start: 7784, end: 7859, text: "dan harga melanjutkan kenaikan hingga awal Agustus" },
  { start: 7866, end: 7941, text: "menuju sekitar 20.350." },
  { start: 7951, end: 8037, text: "Jadi, bullish bias-nya datang dari trend yang masih terjaga." },
  { start: 8056, end: 8127, text: "Squeeze hanya memberi tahu bahwa pergerakan besar" },
  { start: 8131, end: 8160, text: "mungkin segera terjadi." },
  { start: 8182, end: 8206, text: "Dalam kasus ini," },
  { start: 8206, end: 8285, text: "arah breakout sesuai dengan trend yang sudah terbentuk." },
  { start: 8295, end: 8363, text: "Ingat, indikator tidak pernah memimpin harga." },
  { start: 8379, end: 8430, text: "Indikator mengikuti data yang sudah terjadi," },
  { start: 8441, end: 8550, text: "lalu membantu mengonfirmasi atau mempertanyakan analisismu." },
  { start: 8559, end: 8628, text: "Gunakan moving average untuk membaca trend," },
  { start: 8643, end: 8724, text: "Bollinger Bands untuk melihat perubahan volatility," },
  { start: 8739, end: 8799, text: "dan tetap mulai dari price action." },
  { start: 8811, end: 8863, text: "Tapi jangan pernah mengambil keputusan" },
  { start: 8870, end: 8919, text: "hanya karena satu indikator." },
];
