/**
 * subtitles.ts — burned-in cues, in frames at 30fps.
 *
 * TIMING is the corrected SRT's, verbatim. WORDING is that file's too — it is
 * the corrected one, so what is on screen is what was written, not what the
 * first pass transcribed. Generated from `Moving_Average_VO_2_CORRECTED.srt`,
 * never hand-typed.
 *
 * Where the SRT let one cue start before the previous had ended, the earlier
 * cue is truncated to the later one's start. Two cues on screen at once in a
 * band this size is two lines of type overlapping, which the episode forbids.
 *
 * These live in the reserved bottom 108px band, which every scene keeps clear.
 *
 * ⚠ SHIFTED TWICE. Sixty frames of silence were inserted into the voice-over
 * at frame 600 so the roadmap has time to be read; every cue from 601 on moved
 * with it. That pad was then cut to 24 frames (audio only), so every cue that
 * took the first +60 moved back -36 to track the new, shorter pad — cues
 * always follow the AUDIO. SC01 and CG-A's own frame ranges in Composition.tsx
 * were deliberately NOT pulled back to match (Simon: "biarkan overlapping"),
 * so captions inside that span are the one place in the episode that can run
 * ahead of what the video is depicting, until that's reconciled.
 */
export type Cue = { start: number; end: number; text: string };

export const CUES: Cue[] = [
  { start: 0, end: 79, text: "Membaca candlestick dan chart pattern memang powerful." },
  { start: 96, end: 149, text: "Tapi kalau harus cek saham satu per satu," },
  { start: 157, end: 234, text: "prosesnya bisa cukup lama dan butuh mata yang terlatih." },
  { start: 237, end: 282, text: "Di sinilah indikator membantu." },
  { start: 303, end: 366, text: "Indikator mengolah data harga yang sudah ada" },
  { start: 366, end: 421, text: "supaya chart lebih cepat dibaca." },
  { start: 437, end: 483, text: "Bukan menggantikan analisismu," },
  { start: 487, end: 584, text: "tapi membantu menyaring chart dan mengonfirmasi apa yang kamu lihat." },
  { start: 631, end: 691, text: "Kita mulai dari moving average." },
  { start: 703, end: 773, text: "Harga bergerak naik-turun dan penuh noise." },
  { start: 782, end: 845, text: "Moving average mengambil rata-rata harga" },
  { start: 849, end: 875, text: "beberapa hari terakhir," },
  { start: 884, end: 963, text: "lalu menggambarkannya sebagai garis yang lebih halus." },
  { start: 985, end: 1028, text: "Setiap hari, garisnya ikut bergerak." },
  { start: 1035, end: 1117, text: "Noise berkurang dan arah trend jadi lebih mudah terlihat." },
  { start: 1130, end: 1197, text: "Angkanya menunjukkan berapa periode yang dihitung." },
  { start: 1206, end: 1247, text: "Moving average pendek," },
  { start: 1257, end: 1302, text: "misalnya MA20," },
  { start: 1315, end: 1357, text: "bergerak lebih dekat dengan harga" },
  { start: 1363, end: 1403, text: "dan bereaksi lebih cepat." },
  { start: 1416, end: 1447, text: "Moving average panjang," },
  { start: 1451, end: 1481, text: "seperti MA200," },
  { start: 1490, end: 1537, text: "bergerak lebih lambat dan membantu" },
  { start: 1544, end: 1587, text: "melihat trend yang lebih besar." },
  { start: 1607, end: 1661, text: "Jadi, yang pendek lebih responsif." },
  { start: 1664, end: 1707, text: "Yang panjang memberi big picture." },
  { start: 1711, end: 1779, text: "Karena itu, trader sering melihat keduanya." },
  { start: 1789, end: 1827, text: "Ada dua jenis yang sering dipakai:" },
  { start: 1847, end: 1911, text: "SMA dan EMA." },
  { start: 1933, end: 2021, text: "SMA memberi bobot yang sama pada setiap harga." },
  { start: 2045, end: 2142, text: "EMA memberi bobot lebih besar pada harga terbaru," },
  { start: 2153, end: 2192, text: "jadi reaksinya lebih cepat." },
  { start: 2214, end: 2259, text: "Tapi lebih cepat bukan selalu lebih baik," },
  { start: 2267, end: 2333, text: "karena false signal juga bisa lebih sering muncul." },
  { start: 2348, end: 2403, text: "Cara paling sederhana membacanya begini." },
  { start: 2411, end: 2469, text: "Harga di atas moving average yang menanjak" },
  { start: 2472, end: 2511, text: "biasanya menunjukkan uptrend." },
  { start: 2519, end: 2576, text: "Harga di bawah moving average yang menurun" },
  { start: 2580, end: 2613, text: "menunjukkan downtrend." },
  { start: 2618, end: 2652, text: "Perhatikan juga slope-nya." },
  { start: 2654, end: 2714, text: "Semakin curam garisnya, semakin kuat trend." },
  { start: 2717, end: 2777, text: "Kalau datar, market belum punya arah yang jelas." },
  { start: 2801, end: 2835, text: "Jadi, lihat dua hal:" },
  { start: 2846, end: 2917, text: "posisi harga dan arah moving average." },
  { start: 2927, end: 2991, text: "Moving average juga bisa berfungsi sebagai support" },
  { start: 3000, end: 3049, text: "atau resistance yang bergerak." },
  { start: 3059, end: 3123, text: "Dalam uptrend, harga sering pullback ke MA" },
  { start: 3131, end: 3151, text: "yang menanjak," },
  { start: 3151, end: 3216, text: "lalu memantul seperti lantai yang ikut naik." },
  { start: 3239, end: 3267, text: "Dalam downtrend," },
  { start: 3270, end: 3372, text: "MA bisa menahan harga dari atas seperti langit-langit." },
  { start: 3377, end: 3439, text: "Konsepnya sama seperti support dan resistance," },
  { start: 3446, end: 3514, text: "hanya levelnya ikut bergerak bersama harga." },
  { start: 3514, end: 3559, text: "Saat moving average pendek" },
  { start: 3560, end: 3612, text: "menembus moving average panjang dari bawah," },
  { start: 3619, end: 3663, text: "ini disebut golden cross." },
  { start: 3669, end: 3714, text: "Kalau menembus dari atas ke bawah," },
  { start: 3719, end: 3756, text: "disebut death cross." },
  { start: 3773, end: 3866, text: "Tapi jangan anggap crossing sebagai aba-aba entry atau exit." },
  { start: 3872, end: 3929, text: "Moving average bersifat lagging." },
  { start: 3942, end: 3972, text: "Saat crossing muncul," },
  { start: 3979, end: 4043, text: "sebagian pergerakan biasanya sudah terjadi." },
  { start: 4061, end: 4113, text: "Gunakan sebagai konfirmasi trend," },
  { start: 4118, end: 4153, text: "bukan untuk meramal." },
  { start: 4194, end: 4249, text: "Sekarang masuk ke Bollinger Bands." },
  { start: 4259, end: 4327, text: "Di tengahnya ada moving average." },
  { start: 4345, end: 4376, text: "Di atas dan bawahnya," },
  { start: 4381, end: 4457, text: "dua band ikut berubah sesuai volatility —" },
  { start: 4460, end: 4538, text: "seberapa besar pergerakan harga dari rata-ratanya." },
  { start: 4548, end: 4601, text: "Saat market tenang, band menyempit." },
  { start: 4605, end: 4668, text: "Saat pergerakan membesar, band ikut melebar." },
  { start: 4676, end: 4761, text: "Bollinger Bands seperti bernapas mengikuti energi pasar." },
  { start: 4785, end: 4836, text: "Salah satu kondisi yang paling berguna" },
  { start: 4839, end: 4879, text: "diperhatikan adalah squeeze." },
  { start: 4889, end: 4921, text: "Saat band menyempit rapat," },
  { start: 4925, end: 5019, text: "volatility sedang rendah dan harga biasanya bergerak sideways." },
  { start: 5033, end: 5076, text: "Kondisi seperti ini sering muncul" },
  { start: 5079, end: 5124, text: "sebelum pergerakan yang lebih besar." },
  { start: 5137, end: 5208, text: "Tapi squeeze tidak memberi tahu arahnya." },
  { start: 5216, end: 5277, text: "Harga bisa breakout ke atas atau ke bawah." },
  { start: 5298, end: 5342, text: "Jadi, tetap lihat trend" },
  { start: 5342, end: 5409, text: "dan level penting sebelum mengambil kesimpulan." },
  { start: 5420, end: 5503, text: "Ada satu jebakan yang sering terjadi pada pemula." },
  { start: 5514, end: 5539, text: "Dalam trend kuat," },
  { start: 5556, end: 5618, text: "harga bisa terus bergerak dekat upper band." },
  { start: 5627, end: 5714, text: "Jadi, menyentuh upper band bukan otomatis sinyal jual." },
  { start: 5725, end: 5761, text: "Dalam uptrend sehat," },
  { start: 5766, end: 5810, text: "kondisi ini justru bisa menunjukkan" },
  { start: 5814, end: 5874, text: "harga masih bergerak dengan momentum kuat." },
  { start: 5889, end: 5947, text: "Bollinger Bands menunjukkan posisi harga" },
  { start: 5947, end: 6038, text: "terhadap rata-ratanya, bukan memberi keputusan entry atau exit." },
  { start: 6053, end: 6105, text: "Lalu, di mana indikator digunakan?" },
  { start: 6120, end: 6168, text: "Fondasinya tetap price action:" },
  { start: 6189, end: 6227, text: "trend, pattern," },
  { start: 6239, end: 6302, text: "support, dan resistance" },
  { start: 6309, end: 6361, text: "yang kamu baca lebih dulu." },
  { start: 6361, end: 6422, text: "Moving average membantu mengonfirmasi trend." },
  { start: 6427, end: 6464, text: "Bollinger Bands membantu" },
  { start: 6468, end: 6506, text: "melihat apakah volatility" },
  { start: 6510, end: 6554, text: "sedang menyempit atau melebar." },
  { start: 6564, end: 6619, text: "Anggap indikator sebagai second opinion," },
  { start: 6623, end: 6684, text: "bukan alat yang mengambil keputusan untukmu." },
  { start: 6699, end: 6746, text: "Sekarang giliran kamu." },
  { start: 6746, end: 6843, text: "Ini chart GGRM pada Juli 2026." },
  { start: 6890, end: 6955, text: "Harga turun ke moving average yang lebih lambat" },
  { start: 6957, end: 6981, text: "dan menanjak," },
  { start: 6985, end: 7017, text: "yaitu garis ungu," },
  { start: 7023, end: 7055, text: "lalu memantul." },
  { start: 7064, end: 7087, text: "Beberapa hari kemudian," },
  { start: 7087, end: 7145, text: "Bollinger Bands menyempit menjadi squeeze," },
  { start: 7149, end: 7236, text: "sementara harga masih bertahan sedikit di atas middle band." },
  { start: 7236, end: 7303, text: "Menurutmu, apakah uptrend-nya masih bertahan?" },
  { start: 7325, end: 7381, text: "Dan saat band serapat ini," },
  { start: 7386, end: 7438, text: "apa yang perlu kita antisipasi?" },
  { start: 7438, end: 7544, text: "Tiga… dua… satu." },
  { start: 7557, end: 7623, text: "Dan ternyata, harga breakout ke atas." },
  { start: 7634, end: 7693, text: "Moving average yang menanjak sebelumnya" },
  { start: 7695, end: 7729, text: "berhasil menjadi support." },
  { start: 7739, end: 7763, text: "Setelah squeeze," },
  { start: 7766, end: 7812, text: "Bollinger Bands kembali melebar" },
  { start: 7814, end: 7889, text: "dan harga melanjutkan kenaikan hingga awal Agustus" },
  { start: 7896, end: 7971, text: "menuju sekitar 20.350." },
  { start: 7981, end: 8067, text: "Jadi, bullish bias-nya datang dari trend yang masih terjaga." },
  { start: 8086, end: 8157, text: "Squeeze hanya memberi tahu bahwa pergerakan besar" },
  { start: 8161, end: 8190, text: "mungkin segera terjadi." },
  { start: 8212, end: 8236, text: "Dalam kasus ini," },
  { start: 8236, end: 8315, text: "arah breakout sesuai dengan trend yang sudah terbentuk." },
  { start: 8325, end: 8393, text: "Ingat, indikator tidak pernah memimpin harga." },
  { start: 8409, end: 8460, text: "Indikator mengikuti data yang sudah terjadi," },
  { start: 8471, end: 8580, text: "lalu membantu mengonfirmasi atau mempertanyakan analisismu." },
  { start: 8589, end: 8658, text: "Gunakan moving average untuk membaca trend," },
  { start: 8673, end: 8754, text: "Bollinger Bands untuk melihat perubahan volatility," },
  { start: 8769, end: 8829, text: "dan tetap mulai dari price action." },
  { start: 8841, end: 8893, text: "Tapi jangan pernah mengambil keputusan" },
  { start: 8900, end: 8949, text: "hanya karena satu indikator." },
];
