/**
 * subtitles.ts — burned-in subtitle cues (frames @30fps), generated from
 * Chart_ID.srt (Indonesian). These fill the reserved bottom 108px band; no
 * other visual may enter it.
 */
export type SubtitleCue = { start: number; end: number; text: string };

export const SUBTITLES: SubtitleCue[] = [
  { start: 1, end: 108, text: "Pertama kali melihat chart saham, banyak orang langsung berpikir," },
  { start: 108, end: 228, text: "“Ini pasti cuma bisa dibaca profesional. Bukan buat saya.” Garis di mana-mana." },
  { start: 228, end: 313, text: "Candlestick. Indikator bertumpuk sampai chart-nya sendiri hampir tidak terlihat." },
  { start: 313, end: 363, text: "Rasanya rumit bahkan sebelum kamu mulai." },
  { start: 363, end: 487, text: "Padahal, kamu sudah membaca chart sepanjang hidupmu." },
  { start: 487, end: 701, text: "Coba lihat harga cabai: empat puluh ribu per kilogram, turun ke dua puluh ribu, lalu naik lagi." },
  { start: 703, end: 783, text: "Susun angka itu berdasarkan waktu dan hubungkan titiknya. Jadilah sebuah chart." },
  { start: 783, end: 932, text: "Chart saham sama saja—hanya lebih cepat dan melibatkan lebih banyak orang." },
  { start: 932, end: 1086, text: "Kamu sudah tahu harga saham bisa naik dan turun. Tapi kenapa geraknya membentuk pola tertentu?" },
  { start: 1086, end: 1215, text: "Dan bagaimana cara membaca pesan di baliknya? Chart bukan sekadar catatan masa lalu." },
  { start: 1215, end: 1365, text: "Ia merekam setiap keputusan pembeli dan penjual—kapan mereka berani masuk, kapan mereka ragu, dan kapan mereka akhirnya keluar." },
  { start: 1366, end: 1425, text: "Chart juga punya beberapa bentuk." },
  { start: 1425, end: 1575, text: "Line chart menghubungkan harga penutupan. Tampilannya bersih dan mudah dipahami, tetapi banyak cerita tidak terlihat." },
  { start: 1584, end: 1727, text: "Candlestick memberi gambaran lebih lengkap: harga saat dibuka, titik tertinggi," },
  { start: 1727, end: 1878, text: "titik terendah, dan harga penutupan. Empat informasi dalam satu candle." },
  { start: 1878, end: 1997, text: "Karena itulah candlestick menjadi pilihan utama trader yang ingin membaca pergerakan harga dengan lebih detail." },
  { start: 1997, end: 2078, text: "Setiap chart punya dua sumbu." },
  { start: 2078, end: 2176, text: "Sumbu mendatar menunjukkan waktu: kapan pergerakan itu terjadi?" },
  { start: 2176, end: 2245, text: "Sumbu tegak menunjukkan harga: di level berapa?" },
  { start: 2245, end: 2339, text: "Jadi, setiap titik pada chart selalu menjawab dua pertanyaan sekaligus—" },
  { start: 2339, end: 2412, text: "harganya berapa, dan kapan harga itu terbentuk." },
  { start: 2412, end: 2519, text: "Sekarang lihat saham yang sama dalam timeframe berbeda." },
  { start: 2519, end: 2600, text: "Satu candle lima menit merangkum lima menit transaksi." },
  { start: 2600, end: 2679, text: "Candle harian merangkum satu hari bursa." },
  { start: 2679, end: 2749, text: "Candle mingguan merangkum satu minggu perdagangan." },
  { start: 2749, end: 2829, text: "Sahamnya sama dan sejarahnya juga sama." },
  { start: 2829, end: 2917, text: "Namun gambar yang muncul bisa terasa sangat berbeda. Semuanya bergantung pada seberapa dekat atau seberapa jauh kamu memilih untuk melihatnya." },
  { start: 2917, end: 3058, text: "Semakin pendek timeframe, semakin banyak noise yang terlihat—setiap reaksi kecil," },
  { start: 3058, end: 3117, text: "keraguan sesaat, dan kepanikan pasar." },
  { start: 3117, end: 3219, text: "Semakin panjang timeframe, arah besarnya biasanya semakin jelas." },
  { start: 3219, end: 3295, text: "Chart intraday membantu melihat kapan harus bertindak." },
  { start: 3295, end: 3452, text: "Sementara chart mingguan dan bulanan membantu memahami arah besar tempat keputusan itu diambil. Keduanya berguna, tetapi menjawab pertanyaan yang berbeda." },
  { start: 3461, end: 3526, text: "Nah, di sinilah chart menjadi penting: pasar punya ingatan." },
  { start: 3526, end: 3731, text: "Kalau suatu area harga pernah membuat pembeli masuk, area itu sering kembali menarik perhatian." },
  { start: 3737, end: 3865, text: "Ada trader yang pernah membeli di sana, dan ada juga yang menunggu kesempatan kedua." },
  { start: 3865, end: 3984, text: "Ingatan kolektif itu meninggalkan jejak pada chart. Karena manusia mengingat harga, perilaku yang mirip kadang muncul kembali." },
  { start: 3984, end: 4130, text: "Jadi, anggap technical analysis sebagai alat membaca probabilitas, bukan alat meramal masa depan." },
  { start: 4130, end: 4322, text: "Chart menunjukkan apa yang sudah terjadi, pola yang sering berulang, dan posisi pembeli serta penjual saat ini." },
  { start: 4326, end: 4387, text: "Chart tidak menjamin apa yang terjadi berikutnya—" },
  { start: 4387, end: 4426, text: "tidak ada alat yang bisa." },
  { start: 4426, end: 4573, text: "Namun chart memberimu keunggulan: mengambil keputusan dengan informasi, bukan sekadar harapan atau tebakan." },
  { start: 4573, end: 4721, text: "Setiap candle terbentuk karena manusia mengambil keputusan nyata." },
  { start: 4721, end: 4839, text: "Ada rasa takut, keyakinan, kesabaran, euforia, dan kepanikan—" },
  { start: 4839, end: 4886, text: "semuanya terekam di sana." },
  { start: 4886, end: 4940, text: "Chart bukanlah saham itu sendiri." },
  { start: 4940, end: 5041, text: "Chart adalah ingatan pasar tentang semua orang yang pernah memperdagangkannya." },
  { start: 5041, end: 5091, text: "Belajarlah membaca ingatan itu sebelum ikut mengambil keputusan." },
];
