/**
 * subtitles.ts — burned-in subtitle cues (frames @30fps), generated from
 * VIDEO_01_-_Chart_fixed.srt (Indonesian) and, for the four passages cut in
 * later, from each "Extended Part NN.srt". 125 cues. These fill the reserved
 * bottom 108px band; no other visual may enter it.
 *
 * ⚠ THE NINETEEN NEW CUES ARE SPELLED FROM THE SCRIPT, NOT THE SRT. The
 * supplied files came with no punctuation and lower-case openings; the wording
 * follows what is actually spoken, so where the voice says "ya jadi" and the
 * script writes "Jadi,", the subtitle keeps the spoken words and takes the
 * script's punctuation: "Ya, jadi".
 *
 * ⚠ AND EVERY OLD CUE MOVED. Not one of the 106 straddled a cut, so none had
 * to be split or stretched — each simply shifted by however many frames were
 * inserted before it. The last cue still ends exactly on TOTAL_FRAMES.
 *
 * ⚠ ONE CUE IS NOT A SHIFT BUT A REPLACEMENT. "Padahal, kamu sudah membaca
 * chart sepanjang hidupmu." was re-recorded as "Tanpa disadari, …" — a longer
 * opening on the same sentence, which is why the line needed 110 frames where
 * it had 82. Its start and end are measured off the new recording's own
 * speech, not carried over from the old cue.
 */
export type SubtitleCue = { start: number; end: number; text: string };

export const SUBTITLES: SubtitleCue[] = [
  { start: 3, end: 53, text: "Pertama kali melihat chart saham," },
  { start: 58, end: 90, text: "banyak orang langsung berpikir," },
  { start: 106, end: 142, text: "“Ini pasti cuma bisa dibaca" },
  { start: 149, end: 193, text: "profesional. Bukan buat saya.”" },
  { start: 208, end: 235, text: "Garis di mana-mana." },
  { start: 241, end: 267, text: "Candlestick." },
  { start: 272, end: 310, text: "Indikator bertumpuk" },
  { start: 315, end: 392, text: "sampai chart-nya sendiri hampir tidak terlihat." },
  { start: 405, end: 469, text: "Rasanya rumit bahkan sebelum kamu mulai." },
  { start: 492, end: 516, text: "Tapi sebenarnya," },
  { start: 525, end: 608, text: "kita nggak perlu memahami semuanya sekaligus." },
  { start: 620, end: 651, text: "Kita mulai dari dasar," },
  { start: 655, end: 728, text: "lalu pelan-pelan melihat bagaimana semuanya terhubung." },
  { start: 766, end: 867, text: "Tanpa disadari, kamu sudah membaca chart sepanjang hidupmu." },
  { start: 881, end: 918, text: "Coba lihat harga cabai:" },
  { start: 932, end: 975, text: "40.000 per kilogram," },
  { start: 987, end: 1020, text: "turun ke 20.000," },
  { start: 1029, end: 1053, text: "lalu naik lagi." },
  { start: 1064, end: 1119, text: "Susun angka itu berdasarkan waktu" },
  { start: 1128, end: 1170, text: "dan hubungkan titiknya." },
  { start: 1184, end: 1224, text: "Jadilah sebuah chart." },
  { start: 1235, end: 1286, text: "Chart saham sama saja—" },
  { start: 1318, end: 1372, text: "hanya lebih cepat dan melibatkan lebih banyak orang." },
  { start: 1399, end: 1472, text: "Kamu sudah tahu harga saham bisa naik dan turun." },
  { start: 1485, end: 1561, text: "Tapi kenapa geraknya membentuk pola tertentu?" },
  { start: 1581, end: 1655, text: "Dan bagaimana cara membaca pesan di baliknya?" },
  { start: 1667, end: 1744, text: "Chart bukan sekadar catatan masa lalu." },
  { start: 1765, end: 1832, text: "Ia merekam setiap keputusan pembeli dan penjual—" },
  { start: 1840, end: 1874, text: "kapan mereka berani masuk," },
  { start: 1886, end: 1912, text: "kapan mereka ragu," },
  { start: 1916, end: 1963, text: "dan kapan mereka akhirnya keluar." },
  { start: 1981, end: 2053, text: "Chart juga punya beberapa bentuk." },
  { start: 2067, end: 2138, text: "Line chart menghubungkan harga penutupan." },
  { start: 2145, end: 2207, text: "Tampilannya bersih dan mudah dipahami," },
  { start: 2219, end: 2243, text: "tetapi banyak cerita" },
  { start: 2259, end: 2283, text: "tidak terlihat." },
  { start: 2294, end: 2353, text: "Candlestick memberi gambaran lebih lengkap:" },
  { start: 2363, end: 2390, text: "harga saat dibuka," },
  { start: 2396, end: 2420, text: "titik tertinggi," },
  { start: 2426, end: 2453, text: "titik terendah," },
  { start: 2458, end: 2498, text: "dan harga penutupan." },
  { start: 2517, end: 2573, text: "Empat informasi dalam satu candle." },
  { start: 2581, end: 2605, text: "Karena itulah" },
  { start: 2611, end: 2683, text: "candlestick menjadi pilihan utama trader" },
  { start: 2690, end: 2770, text: "yang ingin membaca pergerakan harga dengan lebih detail." },
  { start: 2792, end: 2816, text: "Ya, jadi" },
  { start: 2828, end: 2933, text: "kita sudah punya dasar untuk membaca chart." },
  { start: 2940, end: 2971, text: "Sekarang, kita mulai melihat" },
  { start: 2975, end: 3025, text: "bagaimana waktu dan pergerakan harga" },
  { start: 3033, end: 3074, text: "mengubah apa yang kita lihat." },
  { start: 3090, end: 3145, text: "Setiap chart punya dua sumbu." },
  { start: 3151, end: 3226, text: "Sumbu mendatar menunjukkan waktu:" },
  { start: 3238, end: 3287, text: "kapan pergerakan itu terjadi?" },
  { start: 3301, end: 3377, text: "Sumbu tegak menunjukkan harga: di level berapa?" },
  { start: 3399, end: 3406, text: "Jadi," },
  { start: 3406, end: 3486, text: "setiap titik pada chart selalu menjawab dua pertanyaan" },
  { start: 3491, end: 3529, text: "sekaligus—harganya berapa," },
  { start: 3545, end: 3598, text: "dan kapan harga itu terbentuk." },
  { start: 3612, end: 3657, text: "Sekarang lihat saham yang sama" },
  { start: 3663, end: 3707, text: "dalam timeframe berbeda." },
  { start: 3719, end: 3797, text: "Satu candle 5 menit merangkum 5 menit transaksi." },
  { start: 3807, end: 3879, text: "Candle harian merangkum satu hari bursa." },
  { start: 3886, end: 3943, text: "Candle mingguan merangkum satu minggu" },
  { start: 3951, end: 3975, text: "perdagangan." },
  { start: 3985, end: 4048, text: "Sahamnya sama dan sejarahnya juga sama." },
  { start: 4055, end: 4132, text: "Namun gambar yang muncul bisa terasa sangat berbeda." },
  { start: 4146, end: 4206, text: "Semuanya bergantung pada seberapa dekat" },
  { start: 4211, end: 4239, text: "atau seberapa jauh" },
  { start: 4255, end: 4308, text: "kamu memilih untuk melihatnya." },
  { start: 4327, end: 4350, text: "Sampai di sini," },
  { start: 4350, end: 4374, text: "kita sudah melihat" },
  { start: 4374, end: 4435, text: "bahwa satu saham bisa terlihat berbeda" },
  { start: 4440, end: 4500, text: "hanya karena cara kita melihat waktunya." },
  { start: 4523, end: 4602, text: "Sekarang, kita masuk lebih jauh ke perilaku pasar." },
  { start: 4614, end: 4652, text: "Semakin pendek timeframe," },
  { start: 4657, end: 4711, text: "semakin banyak noise yang terlihat—" },
  { start: 4719, end: 4784, text: "setiap reaksi kecil, keraguan" },
  { start: 4787, end: 4838, text: "sesaat, dan kepanikan pasar." },
  { start: 4855, end: 4890, text: "Semakin panjang timeframe," },
  { start: 4892, end: 4946, text: "arah besarnya biasanya semakin jelas." },
  { start: 4968, end: 5053, text: "Chart intraday membantu melihat kapan harus bertindak." },
  { start: 5060, end: 5150, text: "Sementara chart mingguan dan bulanan membantu memahami" },
  { start: 5162, end: 5226, text: "arah besar tempat keputusan itu diambil." },
  { start: 5245, end: 5275, text: "Keduanya berguna," },
  { start: 5281, end: 5305, text: "tetapi menjawab" },
  { start: 5312, end: 5349, text: "pertanyaan yang berbeda." },
  { start: 5366, end: 5394, text: "Nah, di sinilah" },
  { start: 5409, end: 5442, text: "chart menjadi penting:" },
  { start: 5456, end: 5496, text: "pasar punya ingatan." },
  { start: 5514, end: 5581, text: "Kalau suatu area harga pernah membuat pembeli masuk," },
  { start: 5595, end: 5659, text: "area itu sering kembali menarik perhatian." },
  { start: 5667, end: 5723, text: "Ada trader yang pernah membeli di sana," },
  { start: 5738, end: 5792, text: "dan ada juga yang menunggu kesempatan" },
  { start: 5795, end: 5916, text: "kedua. Ingatan kolektif itu meninggalkan jejak pada chart." },
  { start: 5930, end: 5953, text: "Karena manusia" },
  { start: 5953, end: 5977, text: "mengingat harga," },
  { start: 5989, end: 6023, text: "perilaku yang mirip" },
  { start: 6031, end: 6068, text: "kadang muncul kembali." },
  { start: 6089, end: 6118, text: "Sekarang kita sudah melihat" },
  { start: 6124, end: 6191, text: "bagaimana chart merekam perilaku pasar." },
  { start: 6206, end: 6247, text: "Tapi satu hal masih perlu diingat:" },
  { start: 6258, end: 6343, text: "pola yang terlihat jelas belum tentu memberi kepastian" },
  { start: 6348, end: 6401, text: "tentang apa yang terjadi berikutnya." },
  { start: 6413, end: 6443, text: "Jadi, anggap" },
  { start: 6449, end: 6549, text: "technical analysis sebagai alat membaca probabilitas," },
  { start: 6568, end: 6623, text: "bukan alat meramal masa depan." },
  { start: 6638, end: 6690, text: "Chart menunjukkan apa yang sudah terjadi," },
  { start: 6699, end: 6734, text: "pola yang sering berulang," },
  { start: 6743, end: 6816, text: "dan posisi pembeli serta penjual saat ini." },
  { start: 6832, end: 6914, text: "Chart tidak menjamin apa yang terjadi berikutnya—" },
  { start: 6916, end: 6958, text: "tidak ada alat yang bisa." },
  { start: 6971, end: 7032, text: "Namun chart memberimu keunggulan: mengambil" },
  { start: 7036, end: 7070, text: "keputusan dengan informasi," },
  { start: 7086, end: 7144, text: "bukan sekadar harapan atau tebakan." },
  { start: 7167, end: 7234, text: "Setiap candle terbentuk karena manusia" },
  { start: 7241, end: 7285, text: "mengambil keputusan nyata." },
  { start: 7309, end: 7333, text: "Ada rasa takut," },
  { start: 7337, end: 7381, text: "keyakinan, kesabaran," },
  { start: 7389, end: 7440, text: "euforia, dan kepanikan—" },
  { start: 7445, end: 7486, text: "semuanya terekam di sana." },
  { start: 7495, end: 7555, text: "Chart bukanlah saham itu sendiri." },
  { start: 7575, end: 7615, text: "Chart adalah ingatan pasar" },
  { start: 7629, end: 7704, text: "tentang semua orang yang pernah memperdagangkannya." },
  { start: 7715, end: 7797, text: "Belajarlah membaca ingatan itu sebelum ikut mengambil" },
  { start: 7803, end: 7827, text: "keputusan." },
];
