/**
 * subtitles.ts — burned-in subtitle cues (frames @30fps), generated from
 * VIDEO_01_-_Chart_fixed.srt (Indonesian) and, for the four passages cut in
 * later, from each "Extended Part NN.srt". 125 cues. These fill the reserved
 * bottom 108px band; no other visual may enter it.
 *
 * ⚠ THE NINETEEN NEW CUES ARE SPELLED FROM THE SCRIPT, NOT THE SRT. The
 * supplied files came with no punctuation and lower-case openings; the wording
 * follows what is actually spoken, so where the voice says "ya jadi" and the
 * script writes "Jadi,", the subtitle keeps the spoken words and takes the
 * script's punctuation: "Ya, jadi".
 *
 * ⚠ AND EVERY OLD CUE MOVED. Not one of the 106 straddled a cut, so none had
 * to be split or stretched — each simply shifted by however many frames were
 * inserted before it. The last cue still ends exactly on TOTAL_FRAMES.
 */
export type SubtitleCue = { start: number; end: number; text: string };

export const SUBTITLES: SubtitleCue[] = [
  { start: 3, end: 53, text: "Pertama kali melihat chart saham," },
  { start: 58, end: 90, text: "banyak orang langsung berpikir," },
  { start: 106, end: 142, text: "“Ini pasti cuma bisa dibaca" },
  { start: 149, end: 193, text: "profesional. Bukan buat saya.”" },
  { start: 208, end: 235, text: "Garis di mana-mana." },
  { start: 241, end: 267, text: "Candlestick." },
  { start: 272, end: 310, text: "Indikator bertumpuk" },
  { start: 315, end: 392, text: "sampai chart-nya sendiri hampir tidak terlihat." },
  { start: 405, end: 469, text: "Rasanya rumit bahkan sebelum kamu mulai." },
  { start: 490, end: 514, text: "Tapi sebenarnya," },
  { start: 523, end: 606, text: "kita nggak perlu memahami semuanya sekaligus." },
  { start: 618, end: 649, text: "Kita mulai dari dasar," },
  { start: 653, end: 726, text: "lalu pelan-pelan melihat bagaimana semuanya terhubung." },
  { start: 733, end: 815, text: "Padahal, kamu sudah membaca chart sepanjang hidupmu." },
  { start: 823, end: 860, text: "Coba lihat harga cabai:" },
  { start: 874, end: 917, text: "40.000 per kilogram," },
  { start: 929, end: 962, text: "turun ke 20.000," },
  { start: 971, end: 995, text: "lalu naik lagi." },
  { start: 1006, end: 1061, text: "Susun angka itu berdasarkan waktu" },
  { start: 1070, end: 1112, text: "dan hubungkan titiknya." },
  { start: 1126, end: 1166, text: "Jadilah sebuah chart." },
  { start: 1177, end: 1228, text: "Chart saham sama saja—" },
  { start: 1260, end: 1314, text: "hanya lebih cepat dan melibatkan lebih banyak orang." },
  { start: 1341, end: 1414, text: "Kamu sudah tahu harga saham bisa naik dan turun." },
  { start: 1427, end: 1503, text: "Tapi kenapa geraknya membentuk pola tertentu?" },
  { start: 1523, end: 1597, text: "Dan bagaimana cara membaca pesan di baliknya?" },
  { start: 1609, end: 1686, text: "Chart bukan sekadar catatan masa lalu." },
  { start: 1707, end: 1774, text: "Ia merekam setiap keputusan pembeli dan penjual—" },
  { start: 1782, end: 1816, text: "kapan mereka berani masuk," },
  { start: 1828, end: 1854, text: "kapan mereka ragu," },
  { start: 1858, end: 1905, text: "dan kapan mereka akhirnya keluar." },
  { start: 1923, end: 1995, text: "Chart juga punya beberapa bentuk." },
  { start: 2009, end: 2080, text: "Line chart menghubungkan harga penutupan." },
  { start: 2087, end: 2149, text: "Tampilannya bersih dan mudah dipahami," },
  { start: 2161, end: 2185, text: "tetapi banyak cerita" },
  { start: 2201, end: 2225, text: "tidak terlihat." },
  { start: 2236, end: 2295, text: "Candlestick memberi gambaran lebih lengkap:" },
  { start: 2305, end: 2332, text: "harga saat dibuka," },
  { start: 2338, end: 2362, text: "titik tertinggi," },
  { start: 2368, end: 2395, text: "titik terendah," },
  { start: 2400, end: 2440, text: "dan harga penutupan." },
  { start: 2459, end: 2515, text: "Empat informasi dalam satu candle." },
  { start: 2523, end: 2547, text: "Karena itulah" },
  { start: 2553, end: 2625, text: "candlestick menjadi pilihan utama trader" },
  { start: 2632, end: 2712, text: "yang ingin membaca pergerakan harga dengan lebih detail." },
  { start: 2730, end: 2754, text: "Ya, jadi" },
  { start: 2766, end: 2871, text: "kita sudah punya dasar untuk membaca chart." },
  { start: 2878, end: 2909, text: "Sekarang, kita mulai melihat" },
  { start: 2913, end: 2963, text: "bagaimana waktu dan pergerakan harga" },
  { start: 2971, end: 3012, text: "mengubah apa yang kita lihat." },
  { start: 3032, end: 3087, text: "Setiap chart punya dua sumbu." },
  { start: 3093, end: 3168, text: "Sumbu mendatar menunjukkan waktu:" },
  { start: 3180, end: 3229, text: "kapan pergerakan itu terjadi?" },
  { start: 3243, end: 3319, text: "Sumbu tegak menunjukkan harga: di level berapa?" },
  { start: 3341, end: 3348, text: "Jadi," },
  { start: 3348, end: 3428, text: "setiap titik pada chart selalu menjawab dua pertanyaan" },
  { start: 3433, end: 3471, text: "sekaligus—harganya berapa," },
  { start: 3487, end: 3540, text: "dan kapan harga itu terbentuk." },
  { start: 3554, end: 3599, text: "Sekarang lihat saham yang sama" },
  { start: 3605, end: 3649, text: "dalam timeframe berbeda." },
  { start: 3661, end: 3739, text: "Satu candle 5 menit merangkum 5 menit transaksi." },
  { start: 3749, end: 3821, text: "Candle harian merangkum satu hari bursa." },
  { start: 3828, end: 3885, text: "Candle mingguan merangkum satu minggu" },
  { start: 3893, end: 3917, text: "perdagangan." },
  { start: 3927, end: 3990, text: "Sahamnya sama dan sejarahnya juga sama." },
  { start: 3997, end: 4074, text: "Namun gambar yang muncul bisa terasa sangat berbeda." },
  { start: 4088, end: 4148, text: "Semuanya bergantung pada seberapa dekat" },
  { start: 4153, end: 4181, text: "atau seberapa jauh" },
  { start: 4197, end: 4250, text: "kamu memilih untuk melihatnya." },
  { start: 4263, end: 4286, text: "Sampai di sini," },
  { start: 4286, end: 4310, text: "kita sudah melihat" },
  { start: 4310, end: 4371, text: "bahwa satu saham bisa terlihat berbeda" },
  { start: 4376, end: 4436, text: "hanya karena cara kita melihat waktunya." },
  { start: 4459, end: 4538, text: "Sekarang, kita masuk lebih jauh ke perilaku pasar." },
  { start: 4556, end: 4594, text: "Semakin pendek timeframe," },
  { start: 4599, end: 4653, text: "semakin banyak noise yang terlihat—" },
  { start: 4661, end: 4726, text: "setiap reaksi kecil, keraguan" },
  { start: 4729, end: 4780, text: "sesaat, dan kepanikan pasar." },
  { start: 4797, end: 4832, text: "Semakin panjang timeframe," },
  { start: 4834, end: 4888, text: "arah besarnya biasanya semakin jelas." },
  { start: 4910, end: 4995, text: "Chart intraday membantu melihat kapan harus bertindak." },
  { start: 5002, end: 5092, text: "Sementara chart mingguan dan bulanan membantu memahami" },
  { start: 5104, end: 5168, text: "arah besar tempat keputusan itu diambil." },
  { start: 5187, end: 5217, text: "Keduanya berguna," },
  { start: 5223, end: 5247, text: "tetapi menjawab" },
  { start: 5254, end: 5291, text: "pertanyaan yang berbeda." },
  { start: 5308, end: 5336, text: "Nah, di sinilah" },
  { start: 5351, end: 5384, text: "chart menjadi penting:" },
  { start: 5398, end: 5438, text: "pasar punya ingatan." },
  { start: 5456, end: 5523, text: "Kalau suatu area harga pernah membuat pembeli masuk," },
  { start: 5537, end: 5601, text: "area itu sering kembali menarik perhatian." },
  { start: 5609, end: 5665, text: "Ada trader yang pernah membeli di sana," },
  { start: 5680, end: 5734, text: "dan ada juga yang menunggu kesempatan" },
  { start: 5737, end: 5858, text: "kedua. Ingatan kolektif itu meninggalkan jejak pada chart." },
  { start: 5872, end: 5895, text: "Karena manusia" },
  { start: 5895, end: 5919, text: "mengingat harga," },
  { start: 5931, end: 5965, text: "perilaku yang mirip" },
  { start: 5973, end: 6010, text: "kadang muncul kembali." },
  { start: 6026, end: 6055, text: "Sekarang kita sudah melihat" },
  { start: 6061, end: 6128, text: "bagaimana chart merekam perilaku pasar." },
  { start: 6143, end: 6184, text: "Tapi satu hal masih perlu diingat:" },
  { start: 6195, end: 6280, text: "pola yang terlihat jelas belum tentu memberi kepastian" },
  { start: 6285, end: 6338, text: "tentang apa yang terjadi berikutnya." },
  { start: 6355, end: 6385, text: "Jadi, anggap" },
  { start: 6391, end: 6491, text: "technical analysis sebagai alat membaca probabilitas," },
  { start: 6510, end: 6565, text: "bukan alat meramal masa depan." },
  { start: 6580, end: 6632, text: "Chart menunjukkan apa yang sudah terjadi," },
  { start: 6641, end: 6676, text: "pola yang sering berulang," },
  { start: 6685, end: 6758, text: "dan posisi pembeli serta penjual saat ini." },
  { start: 6774, end: 6856, text: "Chart tidak menjamin apa yang terjadi berikutnya—" },
  { start: 6858, end: 6900, text: "tidak ada alat yang bisa." },
  { start: 6913, end: 6974, text: "Namun chart memberimu keunggulan: mengambil" },
  { start: 6978, end: 7012, text: "keputusan dengan informasi," },
  { start: 7028, end: 7086, text: "bukan sekadar harapan atau tebakan." },
  { start: 7109, end: 7176, text: "Setiap candle terbentuk karena manusia" },
  { start: 7183, end: 7227, text: "mengambil keputusan nyata." },
  { start: 7251, end: 7275, text: "Ada rasa takut," },
  { start: 7279, end: 7323, text: "keyakinan, kesabaran," },
  { start: 7331, end: 7382, text: "euforia, dan kepanikan—" },
  { start: 7387, end: 7428, text: "semuanya terekam di sana." },
  { start: 7437, end: 7497, text: "Chart bukanlah saham itu sendiri." },
  { start: 7517, end: 7557, text: "Chart adalah ingatan pasar" },
  { start: 7571, end: 7646, text: "tentang semua orang yang pernah memperdagangkannya." },
  { start: 7657, end: 7739, text: "Belajarlah membaca ingatan itu sebelum ikut mengambil" },
  { start: 7745, end: 7769, text: "keputusan." },
];
