/**
 * Composition — SC01–SC12 (unchanged) + SC13A–D and SC14A–C (extension) + the
 * ClosingChart continuity group (SC15–16 only). One root <Audio>.
 * durationInFrames = 10663 (05:55.13 @30fps).
 *
 * ⚠ TWO TIMELINES, ONE PICTURE. The English cut plays the picture as authored.
 * The Indonesian cut (`timeline: "indo"`) plays the SAME picture re-timed to
 * its own voice through `indoFrame` (data/indoTimeline.ts, generated by
 * scripts/ta02-indo-timeline.py), with Simon's four new passages cut in and
 * the roadmap (continuity/Roadmap.tsx) playing over each one. Editing a scene
 * still changes both cuts; re-run the script if a scene's length changes.
 */
import React, { useContext } from "react";
import {
  AbsoluteFill,
  Audio,
  Freeze,
  Img,
  Sequence,
  staticFile,
  useCurrentFrame,
  interpolate,
} from "remotion";
import { theme } from "./theme";
import { Scene01 } from "./scenes/Scene01";
import { Scene02 } from "./scenes/Scene02";
import { Scene03 } from "./scenes/Scene03";
import { Scene04 } from "./scenes/Scene04";
import { Scene05 } from "./scenes/Scene05";
import { Scene06 } from "./scenes/Scene06";
import { Scene07 } from "./scenes/Scene07";
import { Scene08 } from "./scenes/Scene08";
import { Scene09 } from "./scenes/Scene09";
import { Scene10 } from "./scenes/Scene10";
import { Scene11 } from "./scenes/Scene11";
import { Scene12 } from "./scenes/Scene12";
import { Scene13A } from "./scenes/Scene13A";
import { Scene13B } from "./scenes/Scene13B";
import { Scene13C } from "./scenes/Scene13C";
import { Scene13D } from "./scenes/Scene13D";
import { Scene14Bbri } from "./scenes/Scene14Bbri";
import { ClosingChart } from "./continuity/ClosingChart";
import { CaseStudyTabs } from "./components/CaseStudyTabs";
import { CaseStudyTabsPair } from "./components/CaseStudyTabsPair";
import { Subtitles } from "./components/Subtitles";
import type { SubtitleCue } from "./subtitles";
import { RoadmapStop, type Stop } from "./continuity/Roadmap";
import { CandleAnatomy, MorningStar } from "./continuity/RoadmapCards";
import {
  INDO_PASSAGES,
  INDO_TOTAL_FRAMES,
  indoFrame,
  indoSegment,
} from "./data/indoTimeline";
import { FilmTracks } from "./tracks";
import { Cut, IndoClock } from "./cut";

export { INDO_TOTAL_FRAMES };

export const TOTAL_FRAMES = 10663; // 05:55.13 @30fps

const FADE = 12; // every scene fades in at its start and out at its end

const SceneFade: React.FC<{
  durationInFrames: number;
  children: React.ReactNode;
  /** false: already fully on at its first frame (a scene continuing a picture). */
  fadeIn?: boolean;
}> = ({ durationInFrames, children, fadeIn = true }) => {
  const f = useCurrentFrame();
  const opacity = interpolate(
    f,
    [0, FADE, durationInFrames - FADE, durationInFrames],
    [fadeIn ? 0 : 1, 1, 1, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );
  return <AbsoluteFill style={{ opacity }}>{children}</AbsoluteFill>;
};

const INDEPENDENT_SCENES: {
  from: number;
  duration: number;
  Component: React.FC;
  /** Track name in the Indonesian cut's timeline (the English cut's tracks are unnamed). */
  label: string;
  /**
   * In the Indonesian cut, no fade-in: the scene takes over the picture the
   * roadmap's push lands on (SC02 continues the Cara-baca-candle drawing).
   */
  continuesIndo?: boolean;
}[] = [
  { from: 0, duration: 240, Component: Scene01, label: "SC01" },
  {
    from: 240,
    duration: 374,
    Component: Scene02,
    label: "SC02",
    continuesIndo: true,
  },
  { from: 614, duration: 460, Component: Scene03, label: "SC03" },
  { from: 1074, duration: 483, Component: Scene04, label: "SC04" },
  { from: 1557, duration: 788, Component: Scene05, label: "SC05" },
  { from: 2345, duration: 808, Component: Scene06, label: "SC06" },
  { from: 3153, duration: 504, Component: Scene07, label: "SC07" },
  { from: 3657, duration: 501, Component: Scene08, label: "SC08" },
  { from: 4158, duration: 921, Component: Scene09, label: "SC09" },
  { from: 5079, duration: 978, Component: Scene10, label: "SC10" },
  { from: 6057, duration: 869, Component: Scene11, label: "SC11" },
  { from: 6926, duration: 847, Component: Scene12, label: "SC12" },
  { from: 7773, duration: 242, Component: Scene13A, label: "SC13A" },
  { from: 8015, duration: 418, Component: Scene13B, label: "SC13B" },
  { from: 8433, duration: 401, Component: Scene13C, label: "SC13C" },
  { from: 8834, duration: 210, Component: Scene13D, label: "SC13D" },
  // 9044–10385 is the BBRI real-footage insert (see the video Sequence below).
];

/** The other Sequences of the film, as [from, end, Indonesian track name]. */
const OVERLAYS: readonly (readonly [number, number, string])[] = [
  [4158, 7766, "SC09–SC12 tabs"],
  [8015, 8834, "SC13B–SC13C tabs"],
  [9044, 10386, "SC14 BBRI"],
  [10386, 10663, "SC15–SC16 closing"],
];

/**
 * The picture — every scene and overlay on its ground, and nothing else (no
 * subtitles, watermark or voice). It is a component of its own so the
 * Indonesian cut can re-time it and the roadmap can freeze it into its cards.
 */
const Film: React.FC = () => {
  const tracks = useContext(FilmTracks);
  const indo = useContext(Cut) === "indo";
  return (
    <AbsoluteFill
      style={{
        backgroundColor: theme.colors.bg,
        fontFamily: theme.type.family,
      }}
    >
      {INDEPENDENT_SCENES.map(
        ({ from, duration, Component, continuesIndo }) => (
          <Sequence
            key={from}
            from={from}
            durationInFrames={duration}
            showInTimeline={tracks}
          >
            <SceneFade
              durationInFrames={duration}
              fadeIn={!(indo && continuesIndo)}
            >
              <Component />
            </SceneFade>
          </Sequence>
        ),
      )}
      {/* SC09–SC12 pattern tab header (unchanged). */}
      <Sequence
        from={4158}
        durationInFrames={7766 - 4158}
        showInTimeline={tracks}
      >
        <CaseStudyTabs />
      </Sequence>
      {/* SC13B–SC13C header — 2-tab replica, persistent across both scenes. */}
      <Sequence from={8015} durationInFrames={819} showInTimeline={tracks}>
        <CaseStudyTabsPair />
      </Sequence>
      {/* SC14 — BBRI real footage with choreographed treatment + overlays. */}
      <Sequence
        from={9044}
        durationInFrames={10386 - 9044}
        showInTimeline={tracks}
      >
        <AbsoluteFill style={{ backgroundColor: theme.colors.bg }}>
          <Scene14Bbri />
        </AbsoluteFill>
      </Sequence>
      {/* Continuity group — SC15 (0–193) + SC16 (193–277). */}
      <Sequence from={10386} durationInFrames={277} showInTimeline={tracks}>
        <SceneFade durationInFrames={277}>
          <ClosingChart />
        </SceneFade>
      </Sequence>
    </AbsoluteFill>
  );
};

/**
 * The Indonesian cut's roadmap stops, one inside each new passage. Each folds
 * the picture held under the passage into the box of the chapter that just
 * ended and pushes into the next; a box that has caught a picture keeps
 * showing it at the stops after.
 *
 * ⚠ THREE STOPS, THREE CHAPTERS. The third passage (SC12 → SC13A) and its
 * voice were cut — "8332-8722 part ini remove aja deh" — and the boxes went to
 * three to match: "(1) Cara baca candle, (2) Makna candle dalam chart, (3)
 * Study Case", each with its own drawing (continuity/RoadmapCards.tsx) until a
 * picture folds into it. SC01 → Introduction → push into (1) → SC02; SC05 →
 * (1), push into (2) → SC06; SC13D → (2), push into (3) → BBRI.
 */
const [P1, P2, P4] = INDO_PASSAGES;
/**
 * Simon: "Scene transisi yang pertama, mulainya dari 538 aja." The first
 * passage still starts at P1.at (284) — SC01 holds its last frame under the
 * voice until the roadmap takes over here; the push still lands on P1.end.
 */
const STOP1_AT = 538;
/**
 * THE STUDY CASE BOX SHOWS THE STUDY CASE ITSELF — Simon: "Yang study case
 * ganti visual deh ... Ganti jadi 9788. Itu adalah visual langsung dari scene
 * study case, jadi ga perlu fade out lagi." 9788 is the first clean frame of
 * the BBRI scene; its box holds that frame (the ORIGINAL frame behind it), and
 * the last stop pushes into it and lands ON 9788 with a cut instead of a
 * dissolve — the live scene there is the same picture, to the pixel.
 */
const STUDY_CASE_AT = 9788;
const STUDY_CASE = indoFrame(STUDY_CASE_AT);
const STOPS: Stop[] = [
  {
    at: STOP1_AT,
    land: null,
    into: 0,
    end: P1.end,
    freeze: P1.xOut,
    previews: [CandleAnatomy, MorningStar, STUDY_CASE],
    /* ⚠ 72, NOT 90 — TA01's own first push. From 538 the swap lands at 622,
       and a 90-frame push set off on that same frame: the grid never came to
       rest, so its ease-out read as no ease at all (Simon: "580-622 kayak
       gaada easy ease nya"). At 72 the grid holds 622-640, the glow comes on
       after it has landed, and then the push. */
    push: 72,
  },
  {
    at: P2.at,
    land: 0,
    into: 1,
    end: P2.end,
    freeze: P2.xOut,
    previews: [P2.xOut, MorningStar, STUDY_CASE],
  },
  {
    at: P4.at,
    land: 1,
    into: 2,
    end: STUDY_CASE_AT,
    dissolve: 0,
    freeze: P4.xOut,
    previews: [P2.xOut, P4.xOut, STUDY_CASE],
  },
];

/**
 * The Indonesian cut's timeline tracks — where each scene, overlay and
 * transition actually sits in THIS cut, fixed. Display only: they render
 * nothing. A scene's span is every output frame showing one of its original
 * frames while no roadmap is up (those are the "Scene Transisi" tracks), so a
 * scene held under a passage before its roadmap starts is counted as itself.
 */
const inRoadmap = (t: number) => STOPS.some((s) => t >= s.at && t < s.end);
const indoSpan = (from: number, end: number) => {
  let a = -1;
  let b = -1;
  for (let t = 0; t < INDO_TOTAL_FRAMES; t++) {
    if (inRoadmap(t)) continue;
    const x = indoFrame(t);
    if (x >= from && x < end) {
      if (a < 0) a = t;
      b = t;
    }
  }
  return { from: a, duration: b - a + 1 };
};
const INDO_TRACKS: { name: string; from: number; duration: number }[] = [
  ...INDEPENDENT_SCENES.map(({ from, duration, label }) => ({
    name: label,
    ...indoSpan(from, from + duration),
  })),
  ...STOPS.map((s, i) => ({
    name: `Scene Transisi ${i + 1}`,
    from: s.at,
    duration: s.end - s.at,
  })),
]
  .sort((a, b) => a.from - b.from)
  .concat(
    OVERLAYS.map(([from, end, name]) => ({ name, ...indoSpan(from, end) })),
  );

export type CandlestickProps = {
  subtitles?: SubtitleCue[];
  audioSrc?: string;
  showSubtitles?: boolean;
  muted?: boolean;
  /** "indo" re-times the picture to the Indonesian voice and adds the roadmap. */
  timeline?: "english" | "indo";
};

export const CandlestickComposition = ({
  subtitles,
  audioSrc = "vo.mp3",
  showSubtitles = true,
  muted = false,
  timeline = "english",
}: CandlestickProps) => {
  const f = useCurrentFrame();
  const indo = timeline === "indo";
  const total = indo ? INDO_TOTAL_FRAMES : TOTAL_FRAMES;
  const [runAt, runFrame, rate] = indoSegment(f);
  const watermarkFade = interpolate(
    f,
    [0, FADE, total - FADE, total],
    [0, 1, 1, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );

  return (
    <AbsoluteFill
      style={{
        backgroundColor: theme.colors.bg,
        fontFamily: theme.type.family,
      }}
    >
      {/* ⚠ A SHIFTING SEQUENCE, AND A FREEZE ONLY ON THE HOLDS. The map is
          runs of "play on" and "hold". A play-on run is the film offset by a
          constant — a Sequence starting at `runAt - runFrame` — so it PLAYS in
          Studio: the BBRI footage runs at full speed. Freezing every frame
          instead rendered the right pictures but made Studio seek the video on
          each one, and the preview fell to 4 fps. The tree is the same shape
          on every frame (only props change), so nothing remounts at a seam.
          Inside the Sequence, Freeze's `frame` is local: exactly `runFrame`. */}
      {indo ? (
        <Cut.Provider value="indo">
          <IndoClock.Provider value={f}>
            <FilmTracks.Provider value={false}>
              <Sequence
                from={runAt - runFrame}
                layout="none"
                showInTimeline={false}
              >
                <Freeze frame={runFrame} active={rate === 0}>
                  <Film />
                </Freeze>
              </Sequence>
              {STOPS.map((stop) => (
                <RoadmapStop key={stop.at} stop={stop} Film={Film} />
              ))}
            </FilmTracks.Provider>
          </IndoClock.Provider>
        </Cut.Provider>
      ) : (
        <Film />
      )}
      {indo &&
        INDO_TRACKS.map((track) => (
          <Sequence
            key={track.name}
            name={track.name}
            from={track.from}
            durationInFrames={track.duration}
            layout="none"
          >
            {null}
          </Sequence>
        ))}
      {/* Burned-in subtitles — per-composition language track (toggle via showSubtitles). */}
      {showSubtitles && <Subtitles cues={subtitles} />}
      {/* Full-frame brand watermark — always on top; fades in at the start, out at the very end. */}
      <AbsoluteFill
        style={{
          opacity: watermarkFade,
          alignItems: "center",
          justifyContent: "center",
          zIndex: 100,
        }}
      >
        <Img
          src={staticFile("watermark.png")}
          style={{ maxWidth: "100%", maxHeight: "100%" }}
        />
      </AbsoluteFill>
      <Audio src={staticFile(audioSrc)} muted={muted} />
    </AbsoluteFill>
  );
};
