/**
 * Composition — SC01–SC12 (unchanged) + SC13A–D and SC14A–C (extension) + the
 * ClosingChart continuity group (SC15–16 only). One root <Audio>.
 * durationInFrames = 10663 (05:55.13 @30fps).
 *
 * ⚠ TWO TIMELINES, ONE PICTURE. The English cut plays the picture as authored.
 * The Indonesian cut (`timeline: "indo"`) plays the SAME picture re-timed to
 * its own voice through `indoFrame` (data/indoTimeline.ts, generated by
 * scripts/ta02-indo-timeline.py), with Simon's four new passages cut in and
 * the roadmap (continuity/Roadmap.tsx) playing over each one. Editing a scene
 * still changes both cuts; re-run the script if a scene's length changes.
 */
import React from "react";
import {
  AbsoluteFill,
  Audio,
  Freeze,
  Img,
  Sequence,
  staticFile,
  useCurrentFrame,
  interpolate,
} from "remotion";
import { theme } from "./theme";
import { Scene01 } from "./scenes/Scene01";
import { Scene02 } from "./scenes/Scene02";
import { Scene03 } from "./scenes/Scene03";
import { Scene04 } from "./scenes/Scene04";
import { Scene05 } from "./scenes/Scene05";
import { Scene06 } from "./scenes/Scene06";
import { Scene07 } from "./scenes/Scene07";
import { Scene08 } from "./scenes/Scene08";
import { Scene09 } from "./scenes/Scene09";
import { Scene10 } from "./scenes/Scene10";
import { Scene11 } from "./scenes/Scene11";
import { Scene12 } from "./scenes/Scene12";
import { Scene13A } from "./scenes/Scene13A";
import { Scene13B } from "./scenes/Scene13B";
import { Scene13C } from "./scenes/Scene13C";
import { Scene13D } from "./scenes/Scene13D";
import { Scene14Bbri } from "./scenes/Scene14Bbri";
import { ClosingChart } from "./continuity/ClosingChart";
import { CaseStudyTabs } from "./components/CaseStudyTabs";
import { CaseStudyTabsPair } from "./components/CaseStudyTabsPair";
import { Subtitles } from "./components/Subtitles";
import type { SubtitleCue } from "./subtitles";
import { RoadmapStop, type Stop } from "./continuity/Roadmap";
import { INDO_PASSAGES, INDO_TOTAL_FRAMES, indoSegment } from "./data/indoTimeline";

export { INDO_TOTAL_FRAMES };

export const TOTAL_FRAMES = 10663; // 05:55.13 @30fps

const FADE = 12; // every scene fades in at its start and out at its end

const SceneFade: React.FC<{
  durationInFrames: number;
  children: React.ReactNode;
}> = ({ durationInFrames, children }) => {
  const f = useCurrentFrame();
  const opacity = interpolate(
    f,
    [0, FADE, durationInFrames - FADE, durationInFrames],
    [0, 1, 1, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );
  return <AbsoluteFill style={{ opacity }}>{children}</AbsoluteFill>;
};

const INDEPENDENT_SCENES: {
  from: number;
  duration: number;
  Component: React.FC;
}[] = [
  { from: 0, duration: 240, Component: Scene01 },
  { from: 240, duration: 374, Component: Scene02 },
  { from: 614, duration: 460, Component: Scene03 },
  { from: 1074, duration: 483, Component: Scene04 },
  { from: 1557, duration: 788, Component: Scene05 },
  { from: 2345, duration: 808, Component: Scene06 },
  { from: 3153, duration: 504, Component: Scene07 },
  { from: 3657, duration: 501, Component: Scene08 },
  { from: 4158, duration: 921, Component: Scene09 },
  { from: 5079, duration: 978, Component: Scene10 },
  { from: 6057, duration: 869, Component: Scene11 },
  { from: 6926, duration: 847, Component: Scene12 },
  { from: 7773, duration: 242, Component: Scene13A },
  { from: 8015, duration: 418, Component: Scene13B },
  { from: 8433, duration: 401, Component: Scene13C },
  { from: 8834, duration: 210, Component: Scene13D },
  // 9044–10385 is the BBRI real-footage insert (see the video Sequence below).
];

/**
 * The picture — every scene and overlay on its ground, and nothing else (no
 * subtitles, watermark or voice). It is a component of its own so the
 * Indonesian cut can re-time it and the roadmap can freeze it into its cards.
 */
const Film: React.FC = () => (
  <AbsoluteFill
    style={{
      backgroundColor: theme.colors.bg,
      fontFamily: theme.type.family,
    }}
  >
    {INDEPENDENT_SCENES.map(({ from, duration, Component }) => (
      <Sequence key={from} from={from} durationInFrames={duration}>
        <SceneFade durationInFrames={duration}>
          <Component />
        </SceneFade>
      </Sequence>
    ))}
    {/* SC09–SC12 pattern tab header (unchanged). */}
    <Sequence from={4158} durationInFrames={7766 - 4158}>
      <CaseStudyTabs />
    </Sequence>
    {/* SC13B–SC13C header — 2-tab replica, persistent across both scenes. */}
    <Sequence from={8015} durationInFrames={819}>
      <CaseStudyTabsPair />
    </Sequence>
    {/* SC14 — BBRI real footage with choreographed treatment + overlays. */}
    <Sequence from={9044} durationInFrames={10386 - 9044}>
      <AbsoluteFill style={{ backgroundColor: theme.colors.bg }}>
        <Scene14Bbri />
      </AbsoluteFill>
    </Sequence>
    {/* Continuity group — SC15 (0–193) + SC16 (193–277). */}
    <Sequence from={10386} durationInFrames={277}>
      <SceneFade durationInFrames={277}>
        <ClosingChart />
      </SceneFade>
    </Sequence>
  </AbsoluteFill>
);

/**
 * The Indonesian cut's four roadmap stops, one inside each new passage. Each
 * folds the picture held under the passage into the box of the chapter that
 * just ended and pushes into the next; a box that has caught a picture keeps
 * showing it at the stops after.
 */
const [P1, P2, P3, P4] = INDO_PASSAGES;
const STOPS: Stop[] = [
  { at: P1.at, land: null, into: 0, end: P1.end, freeze: P1.xOut, previews: [null, null, null, null] },
  { at: P2.at, land: 0, into: 1, end: P2.end, freeze: P2.xOut, previews: [P2.xOut, null, null, null] },
  { at: P3.at, land: 1, into: 2, end: P3.end, freeze: P3.xOut, previews: [P2.xOut, P3.xOut, null, null] },
  { at: P4.at, land: 2, into: 3, end: P4.end, freeze: P4.xOut, previews: [P2.xOut, P3.xOut, P4.xOut, null] },
];

export type CandlestickProps = {
  subtitles?: SubtitleCue[];
  audioSrc?: string;
  showSubtitles?: boolean;
  muted?: boolean;
  /** "indo" re-times the picture to the Indonesian voice and adds the roadmap. */
  timeline?: "english" | "indo";
};

export const CandlestickComposition = ({
  subtitles,
  audioSrc = "vo.mp3",
  showSubtitles = true,
  muted = false,
  timeline = "english",
}: CandlestickProps) => {
  const f = useCurrentFrame();
  const indo = timeline === "indo";
  const total = indo ? INDO_TOTAL_FRAMES : TOTAL_FRAMES;
  const [runAt, runFrame, rate] = indoSegment(f);
  const watermarkFade = interpolate(
    f,
    [0, FADE, total - FADE, total],
    [0, 1, 1, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );

  return (
    <AbsoluteFill
      style={{
        backgroundColor: theme.colors.bg,
        fontFamily: theme.type.family,
      }}
    >
      {/* ⚠ A SHIFTING SEQUENCE, AND A FREEZE ONLY ON THE HOLDS. The map is
          runs of "play on" and "hold". A play-on run is the film offset by a
          constant — a Sequence starting at `runAt - runFrame` — so it PLAYS in
          Studio: the BBRI footage runs at full speed. Freezing every frame
          instead rendered the right pictures but made Studio seek the video on
          each one, and the preview fell to 4 fps. The tree is the same shape
          on every frame (only props change), so nothing remounts at a seam.
          Inside the Sequence, Freeze's `frame` is local: exactly `runFrame`. */}
      {indo ? (
        <Sequence from={runAt - runFrame} layout="none">
          <Freeze frame={runFrame} active={rate === 0}>
            <Film />
          </Freeze>
        </Sequence>
      ) : (
        <Film />
      )}
      {indo && STOPS.map((stop) => <RoadmapStop key={stop.at} stop={stop} Film={Film} />)}
      {/* Burned-in subtitles — per-composition language track (toggle via showSubtitles). */}
      {showSubtitles && <Subtitles cues={subtitles} />}
      {/* Full-frame brand watermark — always on top; fades in at the start, out at the very end. */}
      <AbsoluteFill
        style={{
          opacity: watermarkFade,
          alignItems: "center",
          justifyContent: "center",
          zIndex: 100,
        }}
      >
        <Img src={staticFile("watermark.png")} style={{ maxWidth: "100%", maxHeight: "100%" }} />
      </AbsoluteFill>
      <Audio src={staticFile(audioSrc)} muted={muted} />
    </AbsoluteFill>
  );
};
