/**
 * Composition — "Market Structure", second build.
 *
 * 20 scenes, 10.586 frames as built — 11.832 with Simon's four extended
 * passages (see THE EXTENDED CUT, below). Every `from` and `duration` here is
 * the BUILT film's, VO-locked and taken
 * verbatim from the build spec's timing table — never recomputed from word
 * count. The scenes TILE: each runs until the next one starts, so there is no
 * frame the episode does not own. The voice ends at 10.526; the final 60 frames
 * are the outro hold inside SC20.
 *
 * TWO continuity groups, each a single spanning Sequence, with their member
 * scenes rendering INSIDE them and never at top level. In both cases one chart
 * has to survive a boundary the script runs straight through:
 *
 *   CG-A  1965 → 3042   SC05 + SC06   the staircase SC06 puts numbers on
 *   CG-B  6851 → 7666   SC14 + SC15   the line that stops below the reference
 *                                     and holds there until SC15 resumes it
 *
 * Mounting either half separately would remount its chart and restart the line,
 * which would quietly undo the argument those scenes are making.
 *
 * [NEEDS ASSET] The recorded VO is staged at public/vo-market-structure.mp3.
 * The other two open items are flagged where they bite: data/asii.ts (SC18's
 * CSV) and components/AppSummaryPanel.tsx (SC17's screen recording).
 */
import React, { useContext } from "react";
import {
  AbsoluteFill,
  Audio,
  Freeze,
  random,
  Sequence,
  staticFile,
  useCurrentFrame,
} from "remotion";
import { theme } from "./theme";
import { Scene01 } from "./scenes/Scene01";
import { Scene02 } from "./scenes/Scene02";
import { Scene03 } from "./scenes/Scene03";
import { Scene04 } from "./scenes/Scene04";
import { StaircaseGroup } from "./continuity/StaircaseGroup";
import { Scene07 } from "./scenes/Scene07";
import { Scene08 } from "./scenes/Scene08";
import { Scene09 } from "./scenes/Scene09";
import { Scene10 } from "./scenes/Scene10";
import { Scene11 } from "./scenes/Scene11";
import { Scene12 } from "./scenes/Scene12";
import { Scene13 } from "./scenes/Scene13";
import { FailedPeakGroup } from "./continuity/FailedPeakGroup";
import { Scene16 } from "./scenes/Scene16";
import { Scene17 } from "./scenes/Scene17";
import { Scene18 } from "./scenes/Scene18";
import { Scene19 } from "./scenes/Scene19";
import { Scene20 } from "./scenes/Scene20";
import { Captions } from "./components/Captions";
import { Watermark } from "./components/Watermark";
import { CUES, type Cue } from "./subtitles";
import { EXTENDED_TOTAL_FRAMES, PASSAGES } from "./data/extend";
import { FilmTracks } from "./tracks";
import { RoadmapStop, type Stop } from "./continuity/Roadmap";
import { ShootingStar, StructureLevel } from "./continuity/RoadmapCandles";
import { TuntunLogoCard } from "./components/TuntunLogo";

/** The film as built was 10.586 frames; Simon's four passages make it this. */
export const TOTAL_FRAMES = EXTENDED_TOTAL_FRAMES;

type Mounted = {
  from: number;
  duration: number;
  Component: React.FC;
  label: string;
};

/** Everything except CG-A's and CG-B's member scenes. */
const INDEPENDENT_SCENES: Mounted[] = [
  { from: 0, duration: 462, Component: Scene01, label: "SC01" },
  { from: 462, duration: 466, Component: Scene02, label: "SC02" },
  { from: 928, duration: 522, Component: Scene03, label: "SC03" },
  { from: 1450, duration: 515, Component: Scene04, label: "SC04" },
  { from: 3042, duration: 466, Component: Scene07, label: "SC07" },
  { from: 3508, duration: 406, Component: Scene08, label: "SC08" },
  { from: 3914, duration: 488, Component: Scene09, label: "SC09" },
  { from: 4402, duration: 810, Component: Scene10, label: "SC10" },
  { from: 5212, duration: 643, Component: Scene11, label: "SC11" },
  { from: 5855, duration: 496, Component: Scene12, label: "SC12" },
  { from: 6351, duration: 500, Component: Scene13, label: "SC13" },
  { from: 7666, duration: 542, Component: Scene16, label: "SC16" },
  { from: 8208, duration: 347, Component: Scene17, label: "SC17" },
  { from: 8555, duration: 1055, Component: Scene18, label: "SC18" },
  { from: 9610, duration: 512, Component: Scene19, label: "SC19" },
  { from: 10122, duration: 464, Component: Scene20, label: "SC20" },
];

const CONTINUITY_GROUPS: Mounted[] = [
  { from: 1965, duration: 1077, Component: StaircaseGroup, label: "SC05–SC06" },
  { from: 6851, duration: 815, Component: FailedPeakGroup, label: "SC14–SC15" },
];

/**
 * ═══ THE EXTENDED CUT ═══
 *
 * Simon's four passages (Extended Part 01-04) sit on four scene changes
 * (data/extend.ts, generated by scripts/ta05-extend.py). The film itself is
 * untouched — every scene, CameraCut and Breath still reads the frames it was
 * built on. The output is mapped onto them: before a passage, the film plays;
 * during it, the outgoing scene's last still frame holds; after it, the film
 * plays on, `frames` later. The CameraCut then runs in the silence at the
 * passage's tail, so each next scene lands with its first line as before.
 */
type Run = readonly [number, number, 0 | 1]; // [output frame, film frame, rate]
const RUNS: Run[] = (() => {
  const runs: Run[] = [];
  let t = 0;
  let x = 0;
  for (const p of PASSAGES) {
    runs.push([t, x, 1]);
    x += p.at - t;
    runs.push([p.at, p.hold, 0]);
    t = p.end;
  }
  runs.push([t, x, 1]);
  return runs;
})();
const runAt = (t: number): Run => {
  let r = RUNS[0];
  for (const run of RUNS) if (run[0] <= t) r = run;
  return r;
};
/** The output frame a film frame plays on, for frames outside the holds. */
const outOf = (x: number) =>
  x + PASSAGES.filter((p) => p.hold < x).reduce((s, p) => s + p.frames, 0);

/** The picture: every scene and group, and nothing else. */
const Film: React.FC = () => {
  const tracks = useContext(FilmTracks);
  return (
    <>
      {[...INDEPENDENT_SCENES, ...CONTINUITY_GROUPS].map(
        ({ from, duration, Component }) => (
          <Sequence
            key={from}
            from={from}
            durationInFrames={duration}
            showInTimeline={tracks}
          >
            <Component />
          </Sequence>
        ),
      )}
    </>
  );
};

/**
 * THE SCENE TRANSISI, one stop inside each passage — Simon: "Iya dibuatkan dulu
 * saja Scene Transisinya, visualnya kosongkan, text nya Lorem Ipsum". Each
 * folds the held frame into the box of the chapter that just ended (the first
 * into the Introduction) and pushes into the next. The push lands where the
 * CameraCut into the next scene has finished (the cut's 24 frames run
 * cut−12 → cut+11, under the roadmap), so the scene is settled when the
 * roadmap dissolves off it.
 *
 * A box keeps its drawing (continuity/RoadmapCandles, components/TuntunLogo)
 * until its chapter has been played and a frame of it folded in.
 */
const CUT_TAIL = 23; // the passage ends on film frame cut−12; the CameraCut settles on cut+11
const [P1, P2, P3, P4] = PASSAGES;
const STOPS: Stop[] = [
  {
    at: P1.at,
    land: null,
    into: 0,
    end: P1.end + CUT_TAIL,
    freeze: P1.hold,
    /* ⚠ CONTINUOUS INTO SC02 — "dari scene transisi dibuat continuous aja".
       The box is SC02's own frame at the push's landing (P1.end + CUT_TAIL
       plays film frame P1.end + CUT_TAIL − P1.frames): SC02 opens zoomed on
       the 17 candles that box shows, so the push lands on the scene itself
       and CUTS to it instead of dissolving. */
    previews: [P1.end + CUT_TAIL - P1.frames, StructureLevel, ShootingStar, TuntunLogoCard],
    dissolve: 0,
  },
  {
    at: P2.at,
    land: 0,
    into: 1,
    end: P2.end + CUT_TAIL,
    freeze: P2.hold,
    previews: [P2.hold, StructureLevel, ShootingStar, TuntunLogoCard],
  },
  {
    at: P3.at,
    land: 1,
    into: 2,
    end: P3.end + CUT_TAIL,
    freeze: P3.hold,
    previews: [P2.hold, P3.hold, ShootingStar, TuntunLogoCard],
  },
  {
    at: P4.at,
    land: 2,
    into: 3,
    end: P4.end + CUT_TAIL,
    freeze: P4.hold,
    previews: [P2.hold, P3.hold, P4.hold, TuntunLogoCard],
  },
];

/** Fixed timeline tracks for Studio: where each part sits in the extended cut. Display only. */
const TRACKS = [
  ...[...INDEPENDENT_SCENES, ...CONTINUITY_GROUPS].map(
    ({ from, duration, label }) => ({
      name: label,
      from: outOf(from),
      duration: outOf(from + duration - 1) + 1 - outOf(from),
    }),
  ),
  ...STOPS.map((s, i) => ({
    name: `Scene Transisi ${i + 1}`,
    from: s.at,
    duration: s.end - s.at,
  })),
].sort((a, b) => a.from - b.from);

/**
 * ⚠ THE ROWS REMOUNT TOGETHER, EVERY TIME THIS MODULE LOADS. Simon: "Klo
 * geser2, scene transisi tuh naik turun." Studio orders its rows by when each
 * one first mounted, counted per hot reload; rows that arrived in a later
 * reload than the rest (the four Scene Transisi) share no count with them, so
 * their place was settled through whichever hidden sequences were mounted —
 * and those change as the playhead is dragged through a stop. Keyed on a value
 * drawn once per load, the rows (and the voice, which also has a row) always
 * mount as one batch and keep their order. Studio only: a render reads no key.
 */
const ROWS = String(random(null));

export type MarketStructureProps = {
  cues?: Cue[];
  audioSrc?: string;
  showCaptions?: boolean;
  muted?: boolean;
};

export const MarketStructureComposition = ({
  cues = CUES,
  audioSrc = "vo-market-structure.mp3",
  showCaptions = true,
  muted = false,
}: MarketStructureProps) => {
  const f = useCurrentFrame();
  const [t0, x0, rate] = runAt(f);
  return (
    <AbsoluteFill
      style={{ backgroundColor: theme.color.bg, fontFamily: theme.text.family }}
    >
      {/* ⚠ A SHIFTING SEQUENCE, AND A FREEZE ONLY ON THE HOLDS: a play-on run
          is the film offset by a constant, so the screen recordings PLAY in
          Studio; the tree keeps its shape every frame, so nothing remounts. */}
      <FilmTracks.Provider value={false}>
        <Sequence from={t0 - x0} layout="none" showInTimeline={false}>
          <Freeze frame={x0} active={rate === 0}>
            <Film />
          </Freeze>
        </Sequence>
        {STOPS.map((stop) => (
          <RoadmapStop key={stop.at} stop={stop} Film={Film} />
        ))}
      </FilmTracks.Provider>
      {TRACKS.map((track) => (
        <Sequence
          key={`${ROWS}-${track.name}`}
          name={track.name}
          from={track.from}
          durationInFrames={track.duration}
          layout="none"
        >
          {null}
        </Sequence>
      ))}

      {/* Burned-in captions, inside the reserved band and nowhere else. */}
      {showCaptions && <Captions cues={cues} />}

      {/* Brand watermark — above everything, including the captions. */}
      <Watermark />

      {/* ONE root Audio for the whole episode, aligned at frame 0. */}
      <Audio key={ROWS} src={staticFile(audioSrc)} muted={muted} />
    </AbsoluteFill>
  );
};
