/**
 * extend.ts — GENERATED by scripts/ta05-extend.py. Do not hand-edit.
 *
 * Simon's four extended passages, each on a scene change. For output frames
 * [at, end) the picture holds original frame `hold` (the outgoing scene's last
 * still frame, before its CameraCut moves); everything after plays on, `frames`
 * later. The voice's passage starts at `voiceAt`.
 */
export const EXTENDED_TOTAL_FRAMES = 11832;

export const PASSAGES = [
  { n: 1, cut: 462, hold: 449, at: 450, end: 667, frames: 217, voiceAt: 462 },
  { n: 2, cut: 5212, hold: 5199, at: 5417, end: 5823, frames: 406, voiceAt: 5429 },
  { n: 3, cut: 7666, hold: 7653, at: 8277, end: 8606, frames: 329, voiceAt: 8283 },
  { n: 4, cut: 8555, hold: 8542, at: 9495, end: 9789, frames: 294, voiceAt: 9496 },
] as const;
