#!/usr/bin/env node
/**
 * scripts/srt-to-cues.mjs — corrected SRT → subtitles.ts, at a given fps.
 *
 *   node scripts/srt-to-cues.mjs VO_CORRECTED.srt 60 > src/episodes/020-volume/subtitles.ts
 *
 * TIMING is the SRT's, verbatim. WORDING is the SRT's too — the CORRECTED one,
 * so what is on screen is what was written, not what the first pass
 * transcribed. Never hand-type these.
 *
 * Frames are computed from MILLISECONDS at the target fps — never by doubling
 * an existing 30fps frame count, which would inherit its rounding.
 *
 * Where one cue starts before the previous ended, the earlier one is truncated
 * to the later one's start. Two cues at once in a 108px band is two lines of
 * type overlapping, which is forbidden.
 */
import { readFileSync } from "node:fs";

const [, , path, fpsArg] = process.argv;
if (!path) { console.error("usage: srt-to-cues.mjs <file.srt> [fps=60]"); process.exit(1); }
const fps = Number(fpsArg ?? 60);

const ms = (t) => {
  const [h, m, rest] = t.trim().split(":");
  const [s, f] = rest.split(",");
  return ((+h * 60 + +m) * 60 + +s) * 1000 + +f;
};
const fr = (v) => Math.round((v / 1000) * fps);

const src = readFileSync(path, "utf8").replace(/^\uFEFF/, "");
const cues = src
  .trim()
  .split(/\r?\n\s*\r?\n/)
  .map((b) => {
    const l = b.split(/\r?\n/);
    const [a, z] = l[1].split("-->");
    return { start: ms(a), end: ms(z), text: l.slice(2).join(" ").trim() };
  })
  .filter((c) => c.text);

for (let i = 0; i < cues.length - 1; i++)
  if (cues[i].end > cues[i + 1].start) cues[i].end = cues[i + 1].start;

const esc = (s) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');

console.log(`/**
 * subtitles.ts — burned-in cues, in frames at ${fps}fps.
 *
 * GENERATED by scripts/srt-to-cues.mjs from ${path.split("/").pop()}.
 * Do not edit by hand — fix the SRT and regenerate.
 *
 * These live in the reserved bottom 108px band, which every scene keeps clear.
 */
import type { Cue } from "../../core";

export const CUES: Cue[] = [`);
for (const c of cues)
  console.log(`  { start: ${fr(c.start)}, end: ${fr(c.end)}, text: "${esc(c.text)}" },`);
console.log(`];

/** Last cue out — the floor for the Composition's durationInFrames. */
export const VO_END = ${fr(cues[cues.length - 1].end)};`);
