#!/usr/bin/env python3
"""
ta05-extend.py — Simon's four extended passages cut into TA05-MarketStructure.

    python3 scripts/ta05-extend.py            # subtitles + passage table
    python3 scripts/ta05-extend.py --audio    # ...and rebuild public/vo-market-structure.mp3

Simon: "Cari extended files 01-04 di [VIDEO 19 - Market Structure], lalu
letakkan di timestamp ini: 00.15.14, 02.53.22, 04.15.10, 04.44.24.
Letakkannya di timestamp yang sudah ada saja."

Each passage sits on an existing scene change. The voice is cut in silence at
`audio` (his frames, except 464 -> 462: the next line's cue starts on 462).
The PICTURE holds the outgoing scene's last still frame (`cut - 13`, the frame
before its CameraCut begins to move) for the passage, and the CameraCut then
plays in the silence padded onto the passage's tail, so the next scene still
lands with its first line exactly as before. Each window is therefore the clip
plus `audio - (cut - 12)` frames of silence, and picture and voice both move
on by the same amount.

OUTPUTS
  src/episode20marketstructure/data/extend.ts   the four windows (the map is derived at runtime)
  src/episode20marketstructure/subtitles.ts     cues rippled, the passages' cues added
  public/vo-market-structure.mp3 (--audio)      from vo-market-structure.pre-extend.mp3,
                                                cut on samples (1470 per frame)
"""
import json, os, subprocess, sys
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXT_DIR = os.path.expanduser("~/Documents/01 Academy/VIDEO 19 - Market Structure")
SPF, SR = 1470, 44100

# cut = the scene change (the incoming scene's `from`); audio = the voice's cut, in silence
PASSAGES = [
    dict(n=1, cut=462, audio=462),    # SC01 -> SC02      (Simon: 00.15.14 = 464)
    dict(n=2, cut=5212, audio=5212),  # SC10 -> SC11      (02.53.22 = 5212)
    dict(n=3, cut=7666, audio=7660),  # SC14-15 -> SC16   (04.15.10 = 7660)
    dict(n=4, cut=8555, audio=8544),  # SC17 -> SC18      (04.44.24 = 8544)
]
# The passages' cues: the SRTs' timing, the script's wording (Simon's pasted
# script), keeping the words actually spoken ("nah", "time frame" -> script's
# "timeframe").
TEXT = {
    1: ["Untuk membacanya lebih jelas,", "kita akan mulai dari satu hal sederhana:", "lihat bagaimana harga",
        "membentuk puncak dan lembah."],
    2: ["Sampai di sini,", "kita sudah bisa membedakan tiga kondisi utama:", "harga sedang membentuk tren naik,",
        "tren turun, atau bergerak sideways.", "Nah, sekarang,", "kita lihat bagaimana",
        "struktur ini berhubungan dengan level harga."],
    3: ["Nah, di sinilah", "market structure mulai benar-benar berguna.",
        "Kita bukan cuma melihat apakah harga naik atau turun,", "tapi mencari bukti ketika struktur tersebut",
        "mulai berubah."],
    4: ["Sekarang kita sudah tahu cara membaca arah tren,", "perubahan struktur,",
        "dan pentingnya melihat timeframe yang tepat.", "Tapi teori baru benar-benar terasa",
        "ketika kita melihatnya langsung di chart."],
}
ORIGINAL_FRAMES = 10586


def clip(n):
    return os.path.join(EXT_DIR, f"Extended Part 0{n}", f"Extended Part 0{n}")


def main():
    shift = 0
    for p in PASSAGES:
        dur = float(subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0",
                                    clip(p["n"]) + ".MP3"], capture_output=True, text=True).stdout)
        p["clip"] = int(np.ceil(dur * 30 - 1e-6))
        p["hold"] = p["cut"] - 13                     # the still frame held
        p["pad"] = p["audio"] - (p["cut"] - 12)       # silence after the clip, for the CameraCut
        assert p["pad"] >= 0
        p["frames"] = p["clip"] + p["pad"]
        p["at"] = p["cut"] - 12 + shift               # output frame the hold starts
        p["voiceAt"] = p["audio"] + shift             # output frame the passage's voice starts
        shift += p["frames"]
        p["end"] = p["at"] + p["frames"]
    total = ORIGINAL_FRAMES + shift
    for p in PASSAGES:
        print(f"passage {p['n']}: cut {p['cut']} voice {p['audio']}, clip {p['clip']} + pad {p['pad']} = {p['frames']}, "
              f"hold picture {p['hold']} over output {p['at']}-{p['end']}")
    print("total", total)

    lines = ["/**", " * extend.ts — GENERATED by scripts/ta05-extend.py. Do not hand-edit.", " *",
             " * Simon's four extended passages, each on a scene change. For output frames",
             " * [at, end) the picture holds original frame `hold` (the outgoing scene's last",
             " * still frame, before its CameraCut moves); everything after plays on, `frames`",
             " * later. The voice's passage starts at `voiceAt`.", " */",
             f"export const EXTENDED_TOTAL_FRAMES = {total};", "", "export const PASSAGES = ["]
    for p in PASSAGES:
        lines.append(f"  {{ n: {p['n']}, cut: {p['cut']}, hold: {p['hold']}, at: {p['at']}, end: {p['end']}, frames: {p['frames']}, voiceAt: {p['voiceAt']} }},")
    lines += ["] as const;", ""]
    open(os.path.join(ROOT, "src/episode20marketstructure/data/extend.ts"), "w").write("\n".join(lines))

    # ── subtitles ────────────────────────────────────────────────────────────
    T = lambda y: y + sum(p["frames"] for p in PASSAGES if p["audio"] <= y)
    cues = json.load(open(os.path.join(ROOT, "scripts/ref/ta05-cues.pre-extend.json")))
    for c in cues:
        for p in PASSAGES:
            assert not (c["start"] < p["audio"] < c["end"]), ("cue straddles a cut", c)
    out = [dict(start=T(c["start"]), end=T(c["end"]), text=c["text"]) for c in cues]
    ms = lambda s: (int(s[:2]) * 3600 + int(s[3:5]) * 60 + int(s[6:8])) * 1000 + int(s[9:12])
    for p in PASSAGES:
        blocks = open(clip(p["n"]) + ".srt", encoding="utf-8-sig").read().strip().split("\n\n")
        assert len(blocks) == len(TEXT[p["n"]]), (p["n"], len(blocks))
        for b, text in zip(blocks, TEXT[p["n"]]):
            a, e = b.split("\n")[1].split(" --> ")
            out.append(dict(start=p["voiceAt"] + round(ms(a) * 0.03), end=p["voiceAt"] + round(ms(e) * 0.03), text=text))
    out.sort(key=lambda c: c["start"])
    for a, b in zip(out, out[1:]):
        assert a["end"] <= b["start"], ("overlap", a, b)
    src = open(os.path.join(ROOT, "src/episode20marketstructure/subtitles.ts")).read()
    head = src[: src.index("export const CUES: Cue[] = [")]
    if "EXTENDED" not in head:
        head = head.replace(" * These live in the reserved bottom 108px band",
                            " * EXTENDED: rippled around Simon's four passages, whose own cues are added —\n"
                            " * GENERATED by scripts/ta05-extend.py from scripts/ref/ta05-cues.pre-extend.json.\n"
                            " *\n * These live in the reserved bottom 108px band")
    body = "export const CUES: Cue[] = [\n" + "\n".join(
        f"  {{ start: {c['start']}, end: {c['end']}, text: {json.dumps(c['text'], ensure_ascii=False)} }}," for c in out) + "\n];\n"
    open(os.path.join(ROOT, "src/episode20marketstructure/subtitles.ts"), "w").write(head + body)
    print(f"{len(out)} cues ({len(cues)} rippled, {len(out) - len(cues)} added); last ends {out[-1]['end']}")

    if "--audio" in sys.argv:
        dec = lambda path: np.frombuffer(subprocess.run(["ffmpeg", "-v", "error", "-i", path, "-ac", "2", "-ar", str(SR),
                                                          "-f", "f32le", "-"], capture_output=True).stdout, dtype=np.float32).reshape(-1, 2)
        src = dec(os.path.join(ROOT, "public/vo-market-structure.pre-extend.mp3"))
        parts, prev = [], 0
        for p in PASSAGES:
            parts.append(src[prev * SPF: p["audio"] * SPF])
            c = dec(clip(p["n"]) + ".MP3")
            want = p["frames"] * SPF
            assert len(c) <= want
            parts.append(np.vstack([c, np.zeros((want - len(c), 2), dtype=np.float32)]))
            prev = p["audio"]
        parts.append(src[prev * SPF:])
        out_a = np.vstack(parts)
        dst = os.path.join(ROOT, "public/vo-market-structure.mp3")
        subprocess.run(["ffmpeg", "-v", "error", "-y", "-f", "f32le", "-ar", str(SR), "-ac", "2", "-i", "-",
                        "-c:a", "libmp3lame", "-b:a", "192k", dst], input=out_a.tobytes(), check=True)
        back = dec(dst)[:, 0]
        ref = out_a[:, 0]
        for p in PASSAGES:
            for edge in (p["voiceAt"], p["voiceAt"] + p["frames"]):
                a = edge * SPF - SPF * 3
                seg = ref[a: a + SPF * 6]
                best = max(range(-400, 401), key=lambda lag: float(np.dot(seg, back[a + lag: a + lag + len(seg)])))
                print(f"  join at {edge}: lag {best}")
        print(f"voice {len(out_a) / SPF:.2f} frames -> {dst}")


if __name__ == "__main__":
    main()
