/**
 * subtitles.ts — burned-in cues, in frames at 60fps.
 *
 * GENERATED by scripts/srt-to-cues.mjs from TA_Mistakes_Sub_CORRECTED.srt.
 *
 * ⚠ FIVE PADS HAVE BEEN APPLIED BY HAND SINCE — 30 frames each at 5035, 5175,
 * 7099, 8060 and 8200 — so regenerating from the SRT will undo them unless the
 * SRT is padded first. The audio they belong to is public/vo/ta-mistakes.mp3
 * and the files it replaced are beside it. The last two went in together, in
 * ONE pass from ONE source, so they share one backup: ta-mistakes.pre-pad-
 * 8060+8200.mp3 steps back over both. Their frames are the positions in the
 * timeline BEFORE either was applied.
 *
 * ⚠ THE LAST FOUR WERE VOICE-ONLY, which is a decision with a cost: nothing
 * visual moved with them, so from 5175 the picture leads the voice by 30 frames,
 * from 7099 by 60, from 8060 by 90 and from 8200 by 120. That is Simon's call
 * each time and it is written here rather than left to be discovered in a
 * render.
 *
 * ⚠ WHAT THE LAST TWO ACTUALLY DID, since a running total is not a picture: the
 * only thing drawn across them is round six of the card list, 8060→8270, and it
 * did not move. So the row now arrives 46 frames before the voice names mistake
 * six rather than 16 — the list is up before it is named — and the sentence
 * after it starts at 8262, as the cards are leaving. Everything from SC10 on is
 * blank, so there is nothing else for these two to be out of step with.
 * Do not edit by hand — fix the SRT and regenerate.
 *
 * These live in the reserved bottom 108px band, which every scene keeps clear.
 */
import type { Cue } from "../../core";

export const CUES: Cue[] = [
  { start: 12, end: 227, text: "Bayangin kamu sudah menemukan setup yang kelihatannya lengkap." },
  { start: 227, end: 532, text: "Trend naik, support bertahan, volume menguat, lalu breakout terjadi." },
  { start: 552, end: 622, text: "Kamu masuk dengan yakin." },
  { start: 670, end: 894, text: "Tapi beberapa candle kemudian, harga justru berbalik turun." },
  { start: 928, end: 1060, text: "Apa berarti Technical Analysis-nya gagal?" },
  { start: 1084, end: 1132, text: "Belum tentu." },
  { start: 1148, end: 1428, text: "Intinya: Technical Analysis bekerja dengan probabilitas, bukan kepastian." },
  { start: 1460, end: 1806, text: "Setup yang bagus membantu meningkatkan kualitas keputusan di pasar yang bergerak cepat, tapi tidak pernah menjamin hasil." },
  { start: 1848, end: 1974, text: "Setup lengkap tetap bisa gagal." },
  { start: 2016, end: 2364, text: "Kita mulai dari kesalahan paling berbahaya: masuk tanpa tahu kapan analisis dianggap salah." },
  { start: 2392, end: 2616, text: "Misalnya kamu beli karena support bertahan." },
  { start: 2650, end: 2950, text: "Kalau harga breakdown dan close di bawah support, alasan utama trade itu mulai tidak berlaku." },
  { start: 2976, end: 3076, text: "Setup mulai invalid." },
  { start: 3092, end: 3270, text: "Masalahnya, setelah entry kita sering mulai berharap." },
  { start: 3308, end: 3356, text: "“Sedikit lagi.”" },
  { start: 3376, end: 3432, text: "“Mungkin nanti balik.”" },
  { start: 3462, end: 3800, text: "Karena itu, tentukan invalidation sebelum entry, bukan setelah posisi mulai rugi." },
  { start: 3828, end: 4038, text: "Sejak awal kamu sudah tahu kapan skenario tidak lagi sesuai rencana." },
  { start: 4056, end: 4196, text: "Kesalahan berikutnya datang dari diri kita." },
  { start: 4230, end: 4444, text: "Overtrading terjadi saat kita merasa harus selalu punya posisi." },
  { start: 4488, end: 4900, text: "Padahal kalau trend belum jelas, level belum menarik, atau trigger belum muncul, belum tentu ada trade yang layak." },
  { start: 4900, end: 5022, text: "Tidak trading, juga keputusan." },
  { start: 5070, end: 5172, text: "Lalu ada revenge trading." },
  { start: 5216, end: 5448, text: "Setelah loss, kita ingin cepat mengembalikan kerugian dan buru-buru masuk lagi." },
  { start: 5478, end: 5668, text: "Padahal loss sebelumnya tidak membuat setup berikutnya lebih valid." },
  { start: 5684, end: 5840, text: "Kalau belum ada setup, jawabannya tetap: jangan trade." },
  { start: 5854, end: 6004, text: "Setiap trade baru harus memenuhi aturan yang sama." },
  { start: 6024, end: 6188, text: "Kesalahan berikutnya adalah confirmation bias." },
  { start: 6216, end: 6582, text: "Kita terlalu fokus pada hal yang mendukung skenario, lalu mengabaikan informasi yang berlawanan." },
  { start: 6612, end: 6790, text: "Jangan cuma bertanya: “Apa yang membuat analisisku benar?”" },
  { start: 6804, end: 6977, text: "Tanya juga: “Apa yang bisa membuktikan aku salah?”" },
  { start: 6977, end: 7084, text: "Ini membantu tetap objektif." },
  { start: 7134, end: 7216, text: "Kondisi market juga penting." },
  { start: 7260, end: 7622, text: "Setup yang berjalan baik saat market trending bisa lebih sering gagal saat market sideways atau mulai melemah." },
  { start: 7644, end: 7798, text: "Setup-nya bisa sama, tapi konteksnya berbeda." },
  { start: 7822, end: 8034, text: "Jadi jangan membaca chart tanpa melihat market yang lebih luas." },
  { start: 8106, end: 8224, text: "Jangan terjebak indicator overload." },
  { start: 8262, end: 8536, text: "Menambahkan banyak indikator tidak selalu menambah kualitas analisis." },
  { start: 8566, end: 8856, text: "Kalau beberapa indikator membaca hal yang mirip, kamu mungkin hanya melihat pesan yang sama dalam bentuk berbeda." },
  { start: 8884, end: 9106, text: "Lebih banyak indikator belum tentu berarti lebih banyak insight." },
  { start: 9130, end: 9268, text: "Ada juga hindsight bias." },
  { start: 9290, end: 9438, text: "Setelah harga bergerak, chart sering terlihat sangat jelas." },
  { start: 9470, end: 9756, text: "Padahal saat candle itu belum terbentuk, kita belum tahu apa yang terjadi berikutnya." },
  { start: 9792, end: 9958, text: "Jadi jangan nilai keputusan hanya dari hasil akhir." },
  { start: 9994, end: 10130, text: "Lihat juga apakah prosesnya sudah benar." },
  { start: 10180, end: 10306, text: "Sekarang kita lihat contohnya di ADMR." },
  { start: 10330, end: 10538, text: "Secara jangka panjang, saham ini sebelumnya masih berada dalam uptrend." },
  { start: 10548, end: 10666, text: "Lalu terbentuk descending triangle." },
  { start: 10680, end: 10906, text: "Volume terakhir masih cukup aktif, dan MACD histogram sudah hijau." },
  { start: 10930, end: 11188, text: "Kalau terlalu fokus pada satu skenario, kondisi ini bisa terlihat seperti persiapan rebound." },
  { start: 11200, end: 11280, text: "Apa yang perlu diwaspadai?" },
  { start: 11294, end: 11464, text: "Yang perlu diwaspadai justru perubahan skenario." },
  { start: 11478, end: 11704, text: "Pada 11 Mei 2026, harga break di bawah MA100." },
  { start: 11740, end: 11992, text: "Besoknya, harga mencoba retest, tapi gagal kembali ke atas MA100." },
  { start: 12030, end: 12278, text: "Lalu pada 18 Mei, support descending triangle ikut ditembus." },
  { start: 12292, end: 12448, text: "Kalau bukti berubah, skenario juga harus berubah." },
  { start: 12484, end: 12646, text: "Kesalahan lain adalah asal copy trade orang lain." },
  { start: 12646, end: 13044, text: "Sahamnya mungkin sama, tapi timeframe, harga entry, batas risiko, dan rencana exit bisa berbeda." },
  { start: 13066, end: 13176, text: "Saham sama belum tentu trade-nya sama." },
  { start: 13204, end: 13390, text: "Jadi jangan cuma bertanya: “Dia beli saham apa?”" },
  { start: 13402, end: 13630, text: "Lebih penting pahami kenapa trade itu diambil, dan kapan logikanya dianggap salah." },
  { start: 13642, end: 13810, text: "Kalau logikanya tidak kamu pahami, jangan langsung ikut." },
  { start: 13830, end: 14054, text: "Sebelum entry, tarik semua yang sudah dipelajari menjadi satu proses." },
  { start: 14090, end: 14146, text: "“Trend-nya bagaimana?”" },
  { start: 14160, end: 14226, text: "“Level pentingnya di mana?”" },
  { start: 14248, end: 14296, text: "“Setup-nya apa?”" },
  { start: 14304, end: 14366, text: "“Volume mendukung?”" },
  { start: 14378, end: 14448, text: "“Timeframe lain sejalan?”" },
  { start: 14498, end: 14674, text: "Dan yang paling penting: “apa invalidation-nya?”" },
  { start: 14692, end: 14882, text: "Kalau satu bagian penting belum jelas, trade belum siap." },
  { start: 14918, end: 15022, text: "Lalu cek juga dirimu sendiri." },
  { start: 15050, end: 15348, text: "Kalau ingin entry karena FOMO, kesal, atau ingin membalas loss, berhenti dulu." },
  { start: 15352, end: 15618, text: "Technical Analysis adalah alat bantu keputusan, bukan alat untuk mencari kepastian." },
  { start: 15648, end: 15862, text: "Emosi boleh ada, tapi jangan biarkan emosi mengambil alih proses." },
  { start: 15886, end: 15984, text: "Jadi rule penutupnya sederhana." },
  { start: 16002, end: 16094, text: "Kalau kondisi belum lengkap, tunggu." },
  { start: 16104, end: 16222, text: "Kalau setup sudah invalid, keluar." },
  { start: 16234, end: 16346, text: "Kalau kondisi berubah, evaluasi ulang." },
  { start: 16384, end: 16562, text: "Dan kalau alasan masuknya emosional, jangan dipaksakan." },
  { start: 16578, end: 16770, text: "No trade unless the conditions are met." },
];

/** Last cue out — the floor for the Composition's durationInFrames. */
export const VO_END = 16770;
