/**
 * subtitles.ts — burned-in cues, in frames at 60fps.
 *
 * GENERATED by scripts/srt-to-cues.mjs from TA_Mistakes_Sub_CORRECTED.srt.
 *
 * ⚠ THREE PADS HAVE BEEN APPLIED BY HAND SINCE — 30 frames at 5035, 30 more at
 * 5175 and 30 more at 7099 — so regenerating from the SRT will undo them unless
 * the SRT is padded first. The audio they belong to is public/vo/ta-mistakes.mp3
 * and the files it replaced are beside it, one per pad.
 *
 * ⚠ THE LAST TWO WERE VOICE-ONLY, which is a decision with a cost: nothing
 * visual moved with them, so from 5175 the picture leads the voice by 30 frames
 * and from 7099 by 60. That is Simon's call each time and it is written here
 * rather than left to be discovered in a render.
 * Do not edit by hand — fix the SRT and regenerate.
 *
 * These live in the reserved bottom 108px band, which every scene keeps clear.
 */
import type { Cue } from "../../core";

export const CUES: Cue[] = [
  { start: 12, end: 227, text: "Bayangin kamu sudah menemukan setup yang kelihatannya lengkap." },
  { start: 227, end: 532, text: "Trend naik, support bertahan, volume menguat, lalu breakout terjadi." },
  { start: 552, end: 622, text: "Kamu masuk dengan yakin." },
  { start: 670, end: 894, text: "Tapi beberapa candle kemudian, harga justru berbalik turun." },
  { start: 928, end: 1060, text: "Apa berarti Technical Analysis-nya gagal?" },
  { start: 1084, end: 1132, text: "Belum tentu." },
  { start: 1148, end: 1428, text: "Intinya: Technical Analysis bekerja dengan probabilitas, bukan kepastian." },
  { start: 1460, end: 1806, text: "Setup yang bagus membantu meningkatkan kualitas keputusan di pasar yang bergerak cepat, tapi tidak pernah menjamin hasil." },
  { start: 1848, end: 1974, text: "Setup lengkap tetap bisa gagal." },
  { start: 2016, end: 2364, text: "Kita mulai dari kesalahan paling berbahaya: masuk tanpa tahu kapan analisis dianggap salah." },
  { start: 2392, end: 2616, text: "Misalnya kamu beli karena support bertahan." },
  { start: 2650, end: 2950, text: "Kalau harga breakdown dan close di bawah support, alasan utama trade itu mulai tidak berlaku." },
  { start: 2976, end: 3076, text: "Setup mulai invalid." },
  { start: 3092, end: 3270, text: "Masalahnya, setelah entry kita sering mulai berharap." },
  { start: 3308, end: 3356, text: "“Sedikit lagi.”" },
  { start: 3376, end: 3432, text: "“Mungkin nanti balik.”" },
  { start: 3462, end: 3800, text: "Karena itu, tentukan invalidation sebelum entry, bukan setelah posisi mulai rugi." },
  { start: 3828, end: 4038, text: "Sejak awal kamu sudah tahu kapan skenario tidak lagi sesuai rencana." },
  { start: 4056, end: 4196, text: "Kesalahan berikutnya datang dari diri kita." },
  { start: 4230, end: 4444, text: "Overtrading terjadi saat kita merasa harus selalu punya posisi." },
  { start: 4488, end: 4900, text: "Padahal kalau trend belum jelas, level belum menarik, atau trigger belum muncul, belum tentu ada trade yang layak." },
  { start: 4900, end: 5022, text: "Tidak trading, juga keputusan." },
  { start: 5070, end: 5172, text: "Lalu ada revenge trading." },
  { start: 5216, end: 5448, text: "Setelah loss, kita ingin cepat mengembalikan kerugian dan buru-buru masuk lagi." },
  { start: 5478, end: 5668, text: "Padahal loss sebelumnya tidak membuat setup berikutnya lebih valid." },
  { start: 5684, end: 5840, text: "Kalau belum ada setup, jawabannya tetap: jangan trade." },
  { start: 5854, end: 6004, text: "Setiap trade baru harus memenuhi aturan yang sama." },
  { start: 6024, end: 6188, text: "Kesalahan berikutnya adalah confirmation bias." },
  { start: 6216, end: 6582, text: "Kita terlalu fokus pada hal yang mendukung skenario, lalu mengabaikan informasi yang berlawanan." },
  { start: 6612, end: 6790, text: "Jangan cuma bertanya: “Apa yang membuat analisisku benar?”" },
  { start: 6804, end: 6977, text: "Tanya juga: “Apa yang bisa membuktikan aku salah?”" },
  { start: 6977, end: 7084, text: "Ini membantu tetap objektif." },
  { start: 7134, end: 7216, text: "Kondisi market juga penting." },
  { start: 7260, end: 7622, text: "Setup yang berjalan baik saat market trending bisa lebih sering gagal saat market sideways atau mulai melemah." },
  { start: 7644, end: 7798, text: "Setup-nya bisa sama, tapi konteksnya berbeda." },
  { start: 7822, end: 8034, text: "Jadi jangan membaca chart tanpa melihat market yang lebih luas." },
  { start: 8076, end: 8194, text: "Jangan terjebak indicator overload." },
  { start: 8202, end: 8476, text: "Menambahkan banyak indikator tidak selalu menambah kualitas analisis." },
  { start: 8506, end: 8796, text: "Kalau beberapa indikator membaca hal yang mirip, kamu mungkin hanya melihat pesan yang sama dalam bentuk berbeda." },
  { start: 8824, end: 9046, text: "Lebih banyak indikator belum tentu berarti lebih banyak insight." },
  { start: 9070, end: 9208, text: "Ada juga hindsight bias." },
  { start: 9230, end: 9378, text: "Setelah harga bergerak, chart sering terlihat sangat jelas." },
  { start: 9410, end: 9696, text: "Padahal saat candle itu belum terbentuk, kita belum tahu apa yang terjadi berikutnya." },
  { start: 9732, end: 9898, text: "Jadi jangan nilai keputusan hanya dari hasil akhir." },
  { start: 9934, end: 10070, text: "Lihat juga apakah prosesnya sudah benar." },
  { start: 10120, end: 10246, text: "Sekarang kita lihat contohnya di ADMR." },
  { start: 10270, end: 10478, text: "Secara jangka panjang, saham ini sebelumnya masih berada dalam uptrend." },
  { start: 10488, end: 10606, text: "Lalu terbentuk descending triangle." },
  { start: 10620, end: 10846, text: "Volume terakhir masih cukup aktif, dan MACD histogram sudah hijau." },
  { start: 10870, end: 11128, text: "Kalau terlalu fokus pada satu skenario, kondisi ini bisa terlihat seperti persiapan rebound." },
  { start: 11140, end: 11220, text: "Apa yang perlu diwaspadai?" },
  { start: 11234, end: 11404, text: "Yang perlu diwaspadai justru perubahan skenario." },
  { start: 11418, end: 11644, text: "Pada 11 Mei 2026, harga break di bawah MA100." },
  { start: 11680, end: 11932, text: "Besoknya, harga mencoba retest, tapi gagal kembali ke atas MA100." },
  { start: 11970, end: 12218, text: "Lalu pada 18 Mei, support descending triangle ikut ditembus." },
  { start: 12232, end: 12388, text: "Kalau bukti berubah, skenario juga harus berubah." },
  { start: 12424, end: 12586, text: "Kesalahan lain adalah asal copy trade orang lain." },
  { start: 12586, end: 12984, text: "Sahamnya mungkin sama, tapi timeframe, harga entry, batas risiko, dan rencana exit bisa berbeda." },
  { start: 13006, end: 13116, text: "Saham sama belum tentu trade-nya sama." },
  { start: 13144, end: 13330, text: "Jadi jangan cuma bertanya: “Dia beli saham apa?”" },
  { start: 13342, end: 13570, text: "Lebih penting pahami kenapa trade itu diambil, dan kapan logikanya dianggap salah." },
  { start: 13582, end: 13750, text: "Kalau logikanya tidak kamu pahami, jangan langsung ikut." },
  { start: 13770, end: 13994, text: "Sebelum entry, tarik semua yang sudah dipelajari menjadi satu proses." },
  { start: 14030, end: 14086, text: "“Trend-nya bagaimana?”" },
  { start: 14100, end: 14166, text: "“Level pentingnya di mana?”" },
  { start: 14188, end: 14236, text: "“Setup-nya apa?”" },
  { start: 14244, end: 14306, text: "“Volume mendukung?”" },
  { start: 14318, end: 14388, text: "“Timeframe lain sejalan?”" },
  { start: 14438, end: 14614, text: "Dan yang paling penting: “apa invalidation-nya?”" },
  { start: 14632, end: 14822, text: "Kalau satu bagian penting belum jelas, trade belum siap." },
  { start: 14858, end: 14962, text: "Lalu cek juga dirimu sendiri." },
  { start: 14990, end: 15288, text: "Kalau ingin entry karena FOMO, kesal, atau ingin membalas loss, berhenti dulu." },
  { start: 15292, end: 15558, text: "Technical Analysis adalah alat bantu keputusan, bukan alat untuk mencari kepastian." },
  { start: 15588, end: 15802, text: "Emosi boleh ada, tapi jangan biarkan emosi mengambil alih proses." },
  { start: 15826, end: 15924, text: "Jadi rule penutupnya sederhana." },
  { start: 15942, end: 16034, text: "Kalau kondisi belum lengkap, tunggu." },
  { start: 16044, end: 16162, text: "Kalau setup sudah invalid, keluar." },
  { start: 16174, end: 16286, text: "Kalau kondisi berubah, evaluasi ulang." },
  { start: 16324, end: 16502, text: "Dan kalau alasan masuknya emosional, jangan dipaksakan." },
  { start: 16518, end: 16710, text: "No trade unless the conditions are met." },
];

/** Last cue out — the floor for the Composition's durationInFrames. */
export const VO_END = 16710;
