/**
 * subtitles.ts — burned-in subtitle cues (frames @30fps), generated from Chart-corrected.srt.
 */
export type SubtitleCue = { start: number; end: number; text: string };

export const SUBTITLES: SubtitleCue[] = [
  { start: 1, end: 108, text: "The first time most people see a stock chart, they think the same thing:" },
  { start: 108, end: 228, text: "\"This is for professionals. Not for me.\" Lines everywhere." },
  { start: 228, end: 313, text: "Candles. Indicators stacked on top of each other." },
  { start: 313, end: 363, text: "But here's the thing —" },
  { start: 363, end: 487, text: "you've been reading charts your whole life. You just didn't call it that." },
  { start: 487, end: 701, text: "Think about chili prices: 40,000 per kilogram, then 20,000, then back to 35,000." },
  { start: 703, end: 783, text: "Plot that over time and you've drawn a chart." },
  { start: 783, end: 932, text: "A stock chart is no different — just faster, with more people involved." },
  { start: 932, end: 1086, text: "You already know a stock's price moves up and down. But why does it move the way it does —" },
  { start: 1086, end: 1215, text: "and how do you read what it's telling you? A price chart isn't just history." },
  { start: 1215, end: 1365, text: "It's a record of every decision every buyer and seller has ever made on that stock." },
  { start: 1366, end: 1425, text: "Charts come in different forms." },
  { start: 1425, end: 1575, text: "A line chart connects closing prices — clean, but it hides a lot." },
  { start: 1584, end: 1727, text: "A candlestick chart shows more: where the price opened, how high it went," },
  { start: 1727, end: 1878, text: "how low it fell, and where it closed. Four data points instead of one —" },
  { start: 1878, end: 1997, text: "which is why candlesticks are the standard for serious traders." },
  { start: 1997, end: 2078, text: "Every chart runs on two axes." },
  { start: 2078, end: 2176, text: "Horizontal: when did this happen?" },
  { start: 2176, end: 2245, text: "Vertical: at what price?" },
  { start: 2245, end: 2339, text: "Every point on a chart is the answer to both at once —" },
  { start: 2339, end: 2412, text: "price X, at time Y." },
  { start: 2412, end: 2519, text: "Look at the same stock across different timeframes." },
  { start: 2519, end: 2600, text: "A 5-minute candle is 5 minutes of trading." },
  { start: 2600, end: 2679, text: "A daily candle is one full trading day." },
  { start: 2679, end: 2749, text: "A weekly candle is five days." },
  { start: 2749, end: 2829, text: "Same stock, same history —" },
  { start: 2829, end: 2917, text: "a completely different picture depending on where you stand." },
  { start: 2917, end: 3058, text: "The shorter the timeframe, the more noise — every small reaction," },
  { start: 3058, end: 3117, text: "every moment of indecision." },
  { start: 3117, end: 3219, text: "The longer the timeframe, the clearer the trend." },
  { start: 3219, end: 3295, text: "Intraday charts tell you when to act." },
  { start: 3295, end: 3452, text: "Weekly and monthly charts tell you where — the bigger direction you're acting within." },
  { start: 3461, end: 3526, text: "Here's why reading charts matters:" },
  { start: 3526, end: 3731, text: "markets have memory. When a price level has caused buyers to step in before, it tends to do so again —" },
  { start: 3737, end: 3865, text: "traders who bought there before, and traders waiting for another chance." },
  { start: 3865, end: 3984, text: "That memory shows up in the chart, and it tends to repeat." },
  { start: 3984, end: 4130, text: "Think of technical analysis as a probability tool, not a prediction tool." },
  { start: 4130, end: 4322, text: "A chart shows what has happened, what patterns tend to repeat, and where buyers and sellers currently stand." },
  { start: 4326, end: 4387, text: "It doesn't guarantee what's next —" },
  { start: 4387, end: 4426, text: "nothing does." },
  { start: 4426, end: 4573, text: "What it gives you is an edge: deciding with information instead of a guess." },
  { start: 4573, end: 4721, text: "Every candle was placed there by a real person making a real decision —" },
  { start: 4721, end: 4839, text: "fear, conviction, patience, panic," },
  { start: 4839, end: 4886, text: "all of it recorded." },
  { start: 4886, end: 4940, text: "The chart isn't the stock." },
  { start: 4940, end: 5041, text: "It's the market's memory of everyone who ever traded it." },
  { start: 5041, end: 5091, text: "Learn to read the memory." },
];
